import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'de' | 'my';

const DESC_KEYS: Record<string, string> = {
    'Heavy rain expected. Avoid low-lying areas.': 'heavyRainExpected',
    'Stay hydrated and avoid direct sun.': 'stayHydrated',
    'Street flooded near the park': 'streetFloodedNearPark',
    'Small brush fire spotted': 'smallBrushFireSpotted',
    'Earthquake Warning': 'earthquakeWarning',
    'Storm Warning': 'stormWarning',
    'Medical Emergency': 'medicalEmergency',
    'General Alert': 'generalAlert',
    'Structural Fire': 'structuralFire',
    'Building Fire': 'buildingFire',
    'Vehicle Fire': 'vehicleFire',
    'Other': 'other',
};
const REPORT_TYPE_KEYS: Record<string, string> = {
    FLOOD: 'floodType',
    FIRE: 'fireType',
    EARTHQUAKE: 'earthquakeType',
    STORM: 'stormType',
    MEDICAL: 'medicalType',
    GENERAL: 'generalType',
    STRUCTURAL_FIRE: 'structuralFireType',
    BUILDING_FIRE: 'buildingFireType',
    VEHICLE_FIRE: 'vehicleFireType',
    OTHER: 'otherType',
    MAINTENANCE: 'maintenanceType',
    SECURITY: 'securityType',
    EMERGENCY: 'emergencyType',
    POWER_OUTAGE: 'powerOutageType',
    HAZARDOUS_SPILL: 'hazardousSpillType',
};
const ALERT_TITLE_KEYS: Record<string, string> = {
    'Flash Flood Warning': 'flashFloodWarning',
    'Heatwave Advisory': 'heatwaveAdvisory',
    'Earthquake Warning': 'earthquakeWarning',
    'Storm Warning': 'stormWarning',
    'Medical Emergency': 'medicalEmergency',
    'General Alert': 'generalAlert',
    'Structural Fire': 'structuralFire',
    'Building Fire': 'buildingFire',
    'Vehicle Fire': 'vehicleFire',
    'Other': 'other',
    'Maintenance': 'maintenance',
    'Security': 'security',
    'Emergency': 'emergency',
    'Power Outage': 'powerOutage',
    'Hazardous Spill': 'hazardousSpill',
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
    translateDescription: (desc: string) => string;
    translateReportType: (type: string) => string;
    translateAlertTitle: (title: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
    en: {
        // Navigation
        home: 'Home',
        map: 'Map',
        prepare: 'Prepare',
        sos: 'SOS',
        chat: 'Chat',
        menu: 'Menu',
        
        // Header & Menu
        myProfile: 'My Profile',
        settings: 'Setting',
        signOut: 'Sign Out',
        messages: 'Messages',
        notifications: 'Notification',
        directory: 'Directory',
        
        // Home Page
        goodMorning: 'Good Morning',
        goodAfternoon: 'Good Afternoon',
        goodEvening: 'Good Evening',
        status: 'Status',
        monitoring: 'Monitoring',
        checkStatus: 'Check Status',
        viewKit: 'View Kit',
        activeAlerts: 'Active Alerts',
        liveData: 'Live data',
        viewAll: 'View All',
        quickActions: 'Quick Actions',
        reportIncident: 'Report Incident',
        emergencyContacts: 'Emergency Contacts',
        safetyTips: 'Safety Tips',
        nearbyResources: 'Nearby Resources',
        flashFloodWarning: 'Flash Flood Warning',
        heatwaveAdvisory: 'Heatwave Advisory',
        noActiveAlerts: 'No active alerts. Stay safe!',
        offline: 'OFFLINE',
        score: 'Score',
        level: 'Level',
        beginner: 'Beginner',
        awareCitizen: 'Aware Citizen',
        safetyExpert: 'Safety Expert',
        fullyPrepared: 'You are fully prepared!',
        joinSafetyDrill: 'Join a safety drill',
        completeProfile: 'Complete profile info',
        completeEmergencyKit: 'Complete emergency kit',
        nextAction: 'Next Action',
        kitReadiness: 'Kit Readiness',
        profileComplete: 'Profile Complete',
        drillParticipation: 'Drill Participation',
        readinessScore: 'Readiness Score',
        emergencyKit: 'Emergency Kit',
        profileSetup: 'Profile Setup',
        drillTraining: 'Drill Training',
        nextLabel: 'Next:',
        scoreBreakdown: 'Score Breakdown',
        viewScoreBreakdown: 'View Score Breakdown',
        total: 'Total',
        kitReadinessTitle: 'Kit Readiness',
        emergencySuppliesPlans: 'Emergency supplies & plans',
        profileCompletenessTitle: 'Profile Completeness',
        medicalContactDetails: 'Medical & contact details',
        practiceSimulations: 'Practice simulations',
        broadcast: 'Broadcast',
        broadcastAlert: 'Broadcast Alert',
        alertTitle: 'Alert Title',
        alertTitlePlaceholder: 'e.g. Flash Flood Warning',
        severity: 'Severity',
        low: 'Low',
        moderate: 'Moderate',
        high: 'High',
        alertType: 'Type',
        general: 'General',
        flood: 'Flood',
        fire: 'Fire',
        earthquake: 'Earthquake',
        storm: 'Storm',
        description: 'Description',
        descriptionPlaceholder: 'Instructions for the public...',
        sendAlert: 'Send Alert',
        incidentFrequencyLast6h: 'Incident Frequency (Last 6h)',
        incidentFrequencyLast8h: 'Incident Frequency (Last 8h)',
        incidentFrequencyLast24h: 'Incident Frequency (Last 24h)',
        incidentFrequencyByWeek: 'Incident Frequency by Week',
        incidentFrequencyByDay: 'Incident Frequency by Day',
        incidentFrequencyByMonth: 'Incident Frequency by Month',
        incidentFrequencyByYear: 'Incident Frequency by Year',
        incidentFrequencyLast1Month: 'Last 1 month',
        incidentFrequencyLast1Year: 'Last 1 year',
        seismicAlerts: 'Seismic alerts',
        viewOnMap: 'View on map',
        clickToViewLocation: 'Click to view location on map',
        severityLegendHint: 'Hover on Y-axis for severity. Click data points to view location on map.',
        liveCoordinates: 'Live Coordinates',
        weather: 'Weather',
        weatherUnavailable: 'Unavailable',
        syncLiveData: 'Sync live coordinates and weather',
        
        // Profile
        personalInfo: 'Personal Information',
        edit: 'Edit',
        save: 'Save',
        cancel: 'Cancel',
        name: 'Name',
        email: 'Email',
        phone: 'Phone',
        bloodType: 'Blood Type',
        emergencyContact: 'Emergency Contact',
        safetyScore: 'Safety Score',
        xpPoints: 'XP Points',
        volunteer: 'Volunteer',
        profile: 'Profile',
        stats: 'Stats',
        skills: 'Skills',
        achievements: 'Disaster Preparedness Achievements',
        recentActivities: 'Recent Activities',
        uploadImage: 'Upload/Change Image',
        deleteImage: 'Delete Image',
        confirmProfilePicture: 'Confirm Profile Picture',
        saveProfilePictureQuestion: 'Do you want to save this as your profile picture?',
        
        // Settings
        account: 'Account',
        privacy: 'Privacy',
        security: 'Security',
        accountInfo: 'Account Information',
        username: 'Username',
        role: 'Role',
        preferences: 'Preference',
        language: 'Language',
        selectLanguage: 'Select your preferred language',
        english: 'English',
        german: 'German (Deutsch)',
        myanmar: 'Myanmar (မြန်မာ)',
        timeZone: 'Time Zone',
        syncTimeZone: 'Synchronize with local time',
        themeMode: 'Theme Mode',
        chooseAppearance: 'Choose your preferred appearance',
        light: 'Light',
        dark: 'Dark',
        system: 'System',
        systemModeInfo: 'System mode matches your device settings',
        locationServices: 'Location Services',
        locationEnabled: 'Enabled - Tracking your location',
        locationDisabled: 'Disabled - Location access blocked',
        helpSupport: 'Help & Support',
        
        // Directory
        addContact: 'Add Contact',
        searchContacts: 'Search names, roles, city...',
        all: 'All',
        admin: 'Admin',
        emergency: 'Emergency',
        share: 'Share',
        download: 'Download vCard',
        print: 'Print',
        generateQR: 'Generate QR Code',
        delete: 'Delete',
        noContactsFound: 'No contacts found',
        tryAdjusting: 'Try adjusting your search or filters',
        contactInfo: 'Contact Information',
        callSign: 'Call Sign',
        addNewContact: 'Add New Contact',
        required: 'required',
        enterFullName: 'Enter full name',
        enterRole: 'e.g., First Responder, Coordinator',
        enterCallSign: 'e.g., Alpha-1, Bravo-2',
        enterEmail: 'email@example.com',
        enterPhone: '+1-555-0123',
        userType: 'Type',
        user: 'User',
        responder: 'Responder',
        fillRequired: 'Please fill in all required fields (Name, Email, Phone)',
        
        // Chat
        newMessage: 'New Message',
        typeMessage: 'Type a message...',
        send: 'Send',
        encryptedConversation: 'End-to-end encrypted conversation',
        attachments: 'Attachments',
        image: 'Image',
        document: 'Document',
        voiceMessage: 'Voice Message',
        videoCall: 'Video Call',
        liveLocation: 'Live Location',
        
        // System Status
        systemStatus: 'System Status',
        operationalStatus: 'Operational Status',
        alerts: 'Active Alerts',
        gpsSignal: 'GPS Signal',
        userStatus: 'User Status',
        lastUpdated: 'Last Updated',
        safe: 'Safe',
        searching: 'Searching',
        close: 'Close',
        
        // Notifications
        totalNotifications: 'Total',
        unread: 'Unread',
        read: 'Read',
        markAllRead: 'Mark All as Read',
        
        // Common
        loading: 'Loading...',
        error: 'Error',
        success: 'Success',
        confirm: 'Confirm',
        back: 'Back',
        nextButton: 'Next',
        finish: 'Finish',
        yes: 'Yes',
        no: 'No',
        ok: 'OK',

        // Emergency / SOS
        imSafe: "I'm Safe",
        safeStatusUpdated: 'Your status has been updated and shared with responders.',
        returnToDashboard: 'Return to Dashboard',
        sosActivated: 'SOS ACTIVATED',
        emergencyNotified: 'Emergency services have been notified of your location.',
        broadcastingSignal: 'Broadcasting signal...',
        gettingLocation: 'Getting your live location...',
        locationUnavailable: 'Location unavailable (enable GPS)',
        cancelAlert: 'Cancel Alert',
        emergencyResponse: 'Emergency Response',
        shareStatusReport: 'Share your status or report an incident.',
        respondersNotified: 'Responders will be notified.',
        sosHelp: 'SOS / Help',
        reportAnIncident: 'Report an Incident',
        floodPlacementHint: 'The Yangon River corridor has houses along the riverbanks, port areas, and island settlements. Place flood incidents at riverside locations where communities are at risk. Use the map below to set the exact spot.',
        reviewReport: 'Review Report',
        feed: 'Feed',
        history: 'History',
        mySubmissions: 'My Submissions',
        noReportsSubmitted: 'No reports submitted yet.',
        completePreparednessKit: 'Complete Preparedness Kit',
        updateMedicalProfile: 'Update Medical Profile',
        joinDrillSession: 'Join a Drill Session',
        fullyPreparedMessage: 'You are fully prepared! Great job maintaining safety.',
        closeBreakdown: 'Close Breakdown',
        highZone: 'High 76–100',
        midZone: 'Mid 41–75',
        lowZone: 'Low 0–40',
        preparedness: 'Preparedness',
        deleteChecklistConfirm: 'Delete this checklist item?',
        deleteDrillConfirm: 'Delete this drill session?',
        checklist: 'Checklist',
        drills: 'Drills',
        profileSettings: 'Profile Setting',
        appPreferences: 'App Preference',
        notificationSettings: 'Notification Setting',
        emergencyPlan: 'Emergency Plan',
        shareApp: 'Share App',
        signOutConfirm: 'Are you sure you want to sign out?',
        highSeverity: 'High Severity',
        moderateSeverity: 'Moderate Severity',
        lowSeverity: 'Low Severity',
        criticalSeverity: 'Critical Severity',
        drillsAndLogs: 'Drills & Logs',
        checklistProgress: 'Checklist Progress',
        adminMode: 'Admin Mode',
        upcomingDrills: 'Upcoming Drills',
        pastLogs: 'Past Logs',
        editItem: 'Edit Item',
        newChecklistItem: 'New Checklist Item',
        editDrill: 'Edit Drill',
        newDrillSession: 'New Drill Session',
        newTutorialItem: 'New Tutorial',
        editTutorial: 'Edit Tutorial',
        newLearnItem: 'New Learn Item',
        editLearnItem: 'Edit Learn Item',
        learnItemType: 'Type',
        learnItems: 'Learn Items',
        noLearnItems: 'No learn items yet.',
        deleteLearnItemConfirm: 'Delete this learn item?',
        deleteTutorialConfirm: 'Delete this tutorial?',
        noChecklistItems: 'No checklist items.',
        noUpcomingDrills: 'No upcoming drills scheduled.',
        noPastLogs: 'No past logs yet.',
        noNotesRecorded: 'No notes recorded.',
        participants: 'Participants',
        register: 'Register',
        title: 'Title',
        xpPointsLabel: 'XP Points',
        privacyPolicy: 'Privacy Policy',
        privacyControls: 'Privacy Controls',
        complete: 'Complete',
        adminPanel: 'Admin Panel',
        date: 'Date',
        dateLabel: 'Date',
        notSet: 'Not set',
        pushNotifications: 'Push Notifications',
        emailNotifications: 'Email Notifications',
        profileVisibility: 'Profile Visibility',
        shareLocation: 'Share Location',
        deleteAccount: 'Delete Account',
        // System Status
        systemOperational: 'System Operational',
        allSystemsNormal: 'All systems functioning normally.',
        criticalNotifications: 'Critical notifications',
        yourStatus: 'Your Status',
        currentSafetyStatus: 'Current safety status',
        network: 'Network',
        // Chat
        emergencyResponseTeam: 'Emergency Response Team',
        communitySafetyGroup: 'Community Safety Group',
        adminSupport: 'Admin Support',
        localResponders: 'Local Responders',
        aiSafetyAssistant: 'AI Safety Assistant',
        aiTyping: 'AI is typing...',
        aiUnavailableFallback: 'Human responders are offline. AI Assistant is available 24/7 for safety advice.',
        urgentHelp: 'Urgent Help',
        sosSigns: 'SOS Signs',
        emojiUrgentHelp: 'Urgent Help',
        emojiEmergency: 'Emergency',
        emojiWarning: 'Warning',
        emojiMedical: 'Medical',
        emojiFire: 'Fire',
        emojiFlood: 'Flood',
        emojiEarthquake: 'Earthquake',
        emojiOk: 'OK',
        emojiShelter: 'Shelter',
        emojiNoElectricity: 'No electricity',
        emojiNoInternet: 'No internet access',
        emojiWounded: 'Wounded',
        emojiCannotSpeak: 'Cannot speak',
        emojiTrapped: 'Trapped',
        emojiNeedWater: 'Need water',
        emojiNeedFood: 'Need food',
        emojiSilent: 'Silent (quiet)',
        emojiChemical: 'Chemical hazard',
        emojiPoison: 'Poison',
        emojiShooterActive: 'Killer',
        // Profile sections
        activityStatistics: 'Activity Statistics',
        skillsAndCertifications: 'Skills & Certifications',
        suggestedSkills: 'Suggested Skills',
        experiencePoints: 'Experience Points',
        volunteerPoints: 'Volunteer Points',
        levelProgress: 'Level Progress',
        nextLevel: 'Next Level',
        fullName: 'Full Name',
        add: 'Add',
        noSkillsAdded: 'No skills added yet',
        addFirstSkill: 'Add your first skill',
        firstAid: 'First Aid',
        cprCertified: 'CPR Certified',
        fireSafety: 'Fire Safety',
        emergencyResponseSkill: 'Emergency Response',
        searchAndRescue: 'Search & Rescue',
        emergencyKitAchievement: 'Emergency Kit',
        firstAidTrained: 'First Aid Trained',
        homeSafety: 'Home Safety',
        certified: 'Certified',
        // Checklist items (by id for mapping)
        checklistBuildKit: 'Build a basic emergency kit',
        checklistSaveNumbers: 'Save local emergency numbers',
        checklistStoreWater: 'Store 3 days of water (1gal/person/day)',
        checklistStockFood: 'Stock non-perishable food for 3 days',
        checklistCanOpener: 'Manual can opener',
        checklistRadio: 'Battery-powered or hand-crank radio',
        checklistFlashlight: 'Flashlight + extra batteries',
        checklistWhistle: 'Whistle to signal for help',
        checklistWrench: 'Wrench/pliers to turn off utilities',
        checklistLocalMaps: 'Local maps (paper)',
        checklistMedications: 'Prescription medications (7 day supply)',
        checklistDustMask: 'Dust mask (N95) for contaminated air',
        checklistTowelettes: 'Moist towelettes/garbage bags',
        checklistInsurance: 'Copies of insurance policies',
        checklistIdRecords: 'ID and bank account records',
        checklistCash: 'Cash for emergencies',
        checklistSecureFurniture: 'Secure heavy furniture (bookshelves, cabinets) to walls',
        checklistDropCoverHold: 'Practise Drop-Cover-Hold On drill with household',
        checklistGasShutoff: 'Know location of gas shut-off valve',
        checklistSturdyShoes: 'Keep sturdy shoes near bed (for glass/debris)',
        checklistTsunamiRoute: 'Know evacuation route to high ground',
        checklistTsunamiZone: 'Identify tsunami hazard zone and safe meeting point',
        checklistGoBag: 'Have a go-bag ready for rapid evacuation',
        checklistSecureOutdoor: 'Secure or store outdoor items before storm',
        checklistStormShelter: 'Know nearest storm shelter location',
        checklistChargeDevices: 'Charge all devices before storm',
        checklistSmokeDetectors: 'Install and test smoke detectors',
        checklistFireExtinguisher: 'Fire extinguisher in kitchen and near exits',
        checklistEscapePlan: 'Home escape plan with 2 exits per room',
        checklistMeetingPoint: 'Designate outdoor meeting point for household',
        // Drills
        drillAnnualFire: 'Annual Fire Drill',
        drillEarthquake: 'Earthquake Simulation',
        drillActiveShooter: 'Active Shooter Drill',
        evacuation: 'Evacuation',
        lockdown: 'Lockdown',
        // Learn / Tutorials
        learn: 'Learn',
        learnSubtitle: 'Guides, tutorials & resources',
        howToGuides: 'How to use SafeSphere',
        readMore: 'Read More',
        tutorialVideos: 'Tutorial videos & guides',
        externalResources: 'External resources',
        learnMore: 'View tutorials & resources',
        learnReportIncident: 'Report an incident',
        learnReportIncidentDesc: 'Tap SOS or Report Incident to share your location and situation with responders. Add photos and details for faster assistance.',
        learnChecklist: 'Complete your checklist',
        learnChecklistDesc: 'Build your emergency kit step by step. Mark items complete to improve your Safety Score and earn achievements.',
        learnLiveMap: 'Use the Live Command Map',
        learnLiveMapDesc: 'View incidents, resources and responders on the map. Tap markers for details. Enable location for real-time routing.',
        learnChat: 'Chat with responders',
        learnChatDesc: 'Send encrypted messages, share your live location or start a video call. Use SOS emojis for quick status updates.',
        tutorialEmergencyBasics: 'Emergency preparedness basics',
        tutorialEmergencyBasicsDesc: 'How to prepare your home and family for emergencies.',
        tutorialDisasterPrep: 'Disaster preparedness',
        tutorialDisasterPrepDesc: 'Build a kit, make a plan, stay informed.',
        resourceRedCross: 'Emergency preparedness & first aid',
        resourceFEMA: 'Federal emergency management',
        resourceWHO: 'Global health emergencies',
        resourceCDC: 'Public health emergencies',
        achFirstDrill: 'First Drill',
        achProfile: 'Profile',
        achKit: 'Kit Ready',
        achExpert: 'Expert',
        onboardingWelcome: 'Welcome to SafeSphere',
        onboardingWelcomeDesc: 'Stay prepared for emergencies. Build your kit, complete drills, and learn life-saving skills.',
        onboardingPrepare: 'Prepare',
        onboardingPrepareDesc: 'Use the checklist to build your emergency kit, join drills to practise, and earn XP as you progress.',
        onboardingLearn: 'Learn',
        onboardingLearnDesc: 'Watch tutorials and access resources. Visit the Learn section for guides, videos, and expert tips.',
        onboardingReady: "You're ready!",
        onboardingReadyDesc: 'Start with the checklist below, complete drills, and explore tutorials. Stay safe!',
        onboardingGetStarted: "Let's go",
        onboardingViewLearn: 'View Learn & Tutorials',
        onboardingSkip: 'Skip',
        tutorials: 'Tutorials',
        learnAndEarn: 'Learn from videos and earn XP.',
        watchTutorial: 'Watch',
        markComplete: 'Mark Complete',
        completed: 'Completed',
        earnXp: 'Earn {xp} XP',
        noTutorials: 'No tutorials available.',
        tutorialEarthquake: 'Earthquake Safety Video Series',
        tutorialEarthquakeDesc: 'How to prepare for and stay safe during earthquakes.',
        tutorialFirstAid: 'First Aid Basics',
        tutorialFirstAidDesc: 'Learn essential first aid skills for emergencies.',
        tutorialTrauma: 'Counsellor for Trauma',
        tutorialTraumaDesc: 'Helping someone hyperventilating during a panic attack.',
        tutorialCpr: 'CPR & Defibrillator',
        tutorialCprDesc: 'How to perform CPR and use an AED.',
        tutorialEvac: 'Emergency Evacuation',
        tutorialEvacDesc: 'Be Red Cross Ready: 3 steps to preparedness.',
        // Privacy Policy
        yourPrivacyMatters: 'Your Privacy Matters',
        euDataProtection: 'EU Data Protection Compliant',
        privacyIntro: 'SafeSphere is committed to protecting your personal data in accordance with EU GDPR regulations and international privacy standards.',
        dataCollection: '1. Data Collection',
        dataCollectionDesc: 'We collect location data to provide emergency routing and safety alerts. This data is encrypted and only shared with emergency responders when you explicitly trigger an SOS or submit a report.',
        locationNeverSold: 'Your location is never sold to third parties or used for advertising purposes.',
        endToEndEncryption: '2. End-to-End Encryption',
        endToEndEncryptionDesc: 'All team messages are encrypted end-to-end. We cannot read your messages or listen to your calls. Encryption keys are stored locally on your device.',
        aesEncryption: 'AES Encryption',
        zeroAccessPolicy: 'Zero Access Policy',
        userRights: '3. User Rights',
        userRightsDesc: 'You have the right to access, correct, or delete your personal data at any time via the Settings menu or by contacting support.',
        rightToAccess: 'Right to Access Your Data',
        rightToRectification: 'Right to Rectification',
        rightToErasure: 'Right to Erasure (Right to be Forgotten)',
        rightToPortability: 'Right to Data Portability',
        emergencyDisclosure: '4. Emergency Disclosure',
        emergencyDisclosureDesc: 'In life-threatening situations, we may share your last known location with verified emergency services (Police, Fire, EMS) to assist in rescue operations.',
        whenWeShareData: 'When We Share Your Data:',
        triggerSos: 'You trigger an SOS alert',
        emergencyRequest: 'Emergency services request location assistance',
        legalObligation: 'Legal obligation to prevent harm',
        questionsOrConcerns: 'Questions or Concerns?',
        privacyContact: 'If you have any questions about this Privacy Policy or how we handle your data, please contact our Data Protection Officer:',
        allRightsReserved: 'All rights reserved.',
        euGdprCompliant: 'EU GDPR Compliant',
        isoCertified: 'ISO 27001 Certified',
        helpAndSupport: 'Help & Support',
        helpSupportTitle: 'SafeSphere Help & Support',
        emailSupport: 'Email Support',
        responseTime: 'Response time: 2-4 hours',
        emergencyHotline: 'Emergency Hotline',
        liveChat: 'Live Chat',
        liveChatDesc: 'Available 24/7 in app',
        helpCenter: 'Help Center',
        technicalSupport: 'Technical Support',
        emergencyCallNote: 'For life-threatening emergencies, always call your local emergency services immediately (112, 122, 133, 144, 911, etc.).',
        // Settings - Notifications & more
        alertPreferences: 'Alert Preferences',
        deliveryMethods: 'Delivery Methods',
        emergencyAlertsLabel: 'Emergency Alerts',
        reportUpdates: 'Report Updates',
        systemMessages: 'System Messages',
        statusChanges: 'Status changes',
        appUpdates: 'App updates',
        instantMobileAlerts: 'Instant mobile alerts',
        offlineModeFeatures: 'Offline Mode Features',
        offlineFeaturesDesc: 'Enable features that work without internet connection to ensure you can signal rescuers even offline.',
        whyOfflineFeaturesMatter: 'Why Offline Features Matter',
        offlineFeaturesBullets: 'During emergencies, internet may be unavailable. These features ensure you can:',
        bluetoothBeacon: 'Bluetooth Beacon',
        broadcastSosBluetooth: 'Broadcast SOS via Bluetooth',
        gpsLocation: 'GPS Location',
        trackLocationOffline: 'Track location offline',
        offlineMode: 'Offline Mode',
        workWithoutInternet: 'Work without internet',
        localStorageSync: 'Local Storage Sync',
        cacheDataLocally: 'Cache data locally',
        emergencyBeacon: 'Emergency Beacon',
        sendSosWithoutInternet: 'Send SOS without internet',
        dataManagement: 'Data Management',
        downloadMyData: 'Download My Data',
        clearCache: 'Clear Cache',
        clearCacheConfirm: 'Clear all cached data? Your profile and settings will be kept.',
        deleteAccountConfirm: 'Delete your account and all data? This cannot be undone. You will be signed out.',
        passwordAndAuthentication: 'Password & Authentication',
        changePassword: 'Change Password',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmNewPassword: 'Confirm New Password',
        updatePassword: 'Update Password',
        passwordChangedSuccess: 'Password changed successfully!',
        twoFactorAuthentication: 'Two-Factor Authentication',
        extraSecurityLayer: 'Extra Security Layer',
        twoFactorDesc: 'Add an extra layer of security by requiring a verification code when signing in.',
        enable2fa: 'Enable 2FA',
        enableFaceId: 'Enable Face ID',
        twoFactorFaceIdRequirement: 'Activate both Enable 2FA and Face ID in order to authenticate.',
        faceId: 'Face ID',
        faceIdRequirementError: 'Please enable both 2FA and Face ID in Settings > Security to use Face ID authentication.',
        activeSessions: 'Active Sessions',
        currentSession: 'Current Session',
        lastActive: 'Last active',
        endAllOtherSessions: 'End All Other Sessions',
        endAllOtherSessionsConfirm: 'End all other sessions? You will stay signed in on this device.',
        otherDevices: 'Other devices',
        active: 'Active',
        disablingLocationWarning: 'Disabling location services may limit emergency response features and safety alerts.',
        locationDataEncrypted: 'Location data is encrypted and only shared during emergencies. We respect your privacy.',
        syncReportsWhenOnline: 'Queue reports to sync when online',
        offlineBullet1: 'Send distress signals via Bluetooth to nearby devices',
        offlineBullet2: 'Share your GPS location when connection returns',
        offlineBullet3: 'Access cached emergency resources offline',
        // Command Center
        commandCenter: 'Command Center',
        incidents: 'Incidents',
        logistics: 'Logistics',
        triage: 'Triage',
        team: 'Team',
        safetyMap: 'Safety Map',
        // QR Scanner
        qrScanner: 'QR Scanner',
        scanSafesphereQrCodes: 'Scan SafeSphere QR codes',
        rescueCenterFound: 'Rescue Center Found!',
        nearestEmergencyFacilityScanned: 'Nearest emergency facility scanned',
        qrCodeId: 'QR Code ID:',
        scanAgain: 'Scan Again',
        callNow: 'Call Now',
        scanning: 'Scanning...',
        positionQrInFrame: 'Position the QR code within the frame',
        phoneNumberCopied: 'Phone number copied to clipboard!',
        // Auth notifications
        signInSuccess: 'You have successfully signed in.',
        loggedOutSuccess: "You've been logged out!",
        signOutConfirmShort: 'Are you sure you want to logout?',
        // Generic confirm & success
        areYouSure: 'Are you sure!',
        savedSuccessfully: "You've successfully done!",
        deletedSuccessfully: 'Deleted successfully.',
        deleteItemConfirm: 'Are you sure you want to delete this item? This action cannot be undone.',
        permissionDenied: 'Permission Denied',
        permissionDeniedAdmin: 'Permission Denied: Only Admins can delete records.',
        markResolvedArchive: 'Mark as Resolved and Archive?',
        scanQrCode: 'Scan QR Code',
        // Command Center - Incidents, Logistics, Triage, Team
        inventoryLog: 'Inventory Log',
        triageBoard: 'Triage Board',
        teamMembers: 'Team Members',
        searchIncidents: 'Search incidents...',
        statusAll: 'Status: All',
        typeAll: 'Type: All',
        newItem: 'New Item',
        noReportsFound: 'No reports found in this view.',
        // Safety Map Editor
        view: 'View',
        addPoint: 'Add Point',
        drawPath: 'Draw Path',
        evacRoute: 'Evac Route',
        transportRoad: 'Transport Road',
        clear: 'Clear',
        tapMapToPlace: 'Tap map to place',
        tapMapToDraw: 'Tap map to draw',
        pathLabel: 'path',
        newAssetDetails: 'New Asset Details',
        editAsset: 'Edit Asset',
        labelName: 'Label / Name',
        mainExitPlaceholder: 'e.g. Main Exit',
        optionalDetailsPlaceholder: 'Optional details...',
        exit: 'Exit',
        meetingPoint: 'Meeting Point',
        extinguisher: 'Extinguisher',
        hydrant: 'Hydrant',
        // Alert & incident descriptions
        heavyRainExpected: 'Heavy rain expected. Avoid low-lying areas.',
        stayHydrated: 'Stay hydrated and avoid direct sun.',
        floodType: 'FLOOD',
        fireType: 'FIRE',
        streetFloodedNearPark: 'Street flooded near the park',
        smallBrushFireSpotted: 'Small brush fire spotted',
    },
    de: {
        // Navigation
        home: 'Startseite',
        map: 'Karte',
        prepare: 'Vorbereiten',
        sos: 'SOS',
        chat: 'Chat',
        menu: 'Menü',
        
        // Header & Menu
        myProfile: 'Mein Profil',
        settings: 'Einstellungen',
        signOut: 'Abmelden',
        messages: 'Nachrichten',
        notifications: 'Benachrichtigungen',
        directory: 'Verzeichnis',
        
        // Home Page
        goodMorning: 'Guten Morgen',
        goodAfternoon: 'Guten Tag',
        goodEvening: 'Guten Abend',
        status: 'Status',
        monitoring: 'Überwachung',
        checkStatus: 'Status prüfen',
        viewKit: 'Kit ansehen',
        activeAlerts: 'Aktive Alarme',
        liveData: 'Echtzeitdaten',
        viewAll: 'Alle anzeigen',
        quickActions: 'Schnellaktionen',
        reportIncident: 'Vorfall melden',
        emergencyContacts: 'Notfallkontakte',
        safetyTips: 'Sicherheitstipps',
        nearbyResources: 'Ressourcen in der Nähe',
        flashFloodWarning: 'Sturzflutwarnung',
        heatwaveAdvisory: 'Hitzewellenwarnung',
        noActiveAlerts: 'Keine aktiven Alarme. Bleiben Sie sicher!',
        offline: 'OFFLINE',
        score: 'Punkte',
        level: 'Stufe',
        beginner: 'Anfänger',
        awareCitizen: 'Aufmerksamer Bürger',
        safetyExpert: 'Sicherheitsexperte',
        fullyPrepared: 'Sie sind vollständig vorbereitet!',
        joinSafetyDrill: 'An einer Sicherheitsübung teilnehmen',
        completeProfile: 'Profilinformationen vervollständigen',
        completeEmergencyKit: 'Notfallausrüstung vervollständigen',
        nextAction: 'Nächste Aktion',
        kitReadiness: 'Kit-Bereitschaft',
        profileComplete: 'Profil vollständig',
        drillParticipation: 'Übungsteilnahme',
        readinessScore: 'Bereitschaftswert',
        emergencyKit: 'Notfallausrüstung',
        profileSetup: 'Profil-Einrichtung',
        drillTraining: 'Übungstraining',
        nextLabel: 'Nächste:',
        scoreBreakdown: 'Punkteverteilung',
        viewScoreBreakdown: 'Punkteverlauf anzeigen',
        total: 'Gesamt',
        kitReadinessTitle: 'Ausrüstungsbereitschaft',
        emergencySuppliesPlans: 'Notfallvorräte & Pläne',
        profileCompletenessTitle: 'Profilvollständigkeit',
        medicalContactDetails: 'Medizinische & Kontaktdaten',
        practiceSimulations: 'Übungssimulationen',
        broadcast: 'Übertragung',
        broadcastAlert: 'Alarm übertragen',
        alertTitle: 'Alarmtitel',
        alertTitlePlaceholder: 'z.B. Sturzflutwarnung',
        severity: 'Schweregrad',
        low: 'Niedrig',
        moderate: 'Mäßig',
        high: 'Hoch',
        alertType: 'Typ',
        general: 'Allgemein',
        flood: 'Hochwasser',
        fire: 'Feuer',
        earthquake: 'Erdbeben',
        storm: 'Sturm',
        description: 'Beschreibung',
        descriptionPlaceholder: 'Anweisungen für die Öffentlichkeit...',
        sendAlert: 'Alarm senden',
        incidentFrequencyLast6h: 'Vorfallhäufigkeit (Letzte 6h)',
        incidentFrequencyLast8h: 'Vorfallhäufigkeit (Letzte 8h)',
        incidentFrequencyLast24h: 'Vorfallhäufigkeit (Letzte 24h)',
        incidentFrequencyByWeek: 'Vorfallhäufigkeit nach Woche',
        incidentFrequencyByDay: 'Vorfallhäufigkeit nach Tag',
        incidentFrequencyByMonth: 'Vorfallhäufigkeit nach Monat',
        incidentFrequencyByYear: 'Vorfallhäufigkeit nach Jahr',
        incidentFrequencyLast1Month: 'Letzter Monat',
        incidentFrequencyLast1Year: 'Letztes Jahr',
        seismicAlerts: 'Seismische Meldungen',
        viewOnMap: 'Auf Karte anzeigen',
        clickToViewLocation: 'Klicken, um den Standort auf der Karte anzuzeigen',
        severityLegendHint: 'Über Y-Achse fahren für Schweregrad. Datenpunkte anklicken für Standort.',
        liveCoordinates: 'Live-Koordinaten',
        weather: 'Wetter',
        weatherUnavailable: 'Nicht verfügbar',
        syncLiveData: 'Live-Koordinaten und Wetter aktualisieren',
        
        // Profile
        personalInfo: 'Persönliche Informationen',
        edit: 'Bearbeiten',
        save: 'Speichern',
        cancel: 'Abbrechen',
        name: 'Name',
        email: 'E-Mail',
        phone: 'Telefon',
        bloodType: 'Blutgruppe',
        emergencyContact: 'Notfallkontakt',
        safetyScore: 'Sicherheitsbewertung',
        xpPoints: 'XP-Punkte',
        volunteer: 'Freiwillig',
        profile: 'Profil',
        stats: 'Statistiken',
        skills: 'Fähigkeiten',
        achievements: 'Katastrophenvorsorge-Erfolge',
        recentActivities: 'Letzte Aktivitäten',
        uploadImage: 'Bild hochladen/ändern',
        deleteImage: 'Bild löschen',
        confirmProfilePicture: 'Profilbild bestätigen',
        saveProfilePictureQuestion: 'Möchten Sie dieses Bild als Ihr Profilbild speichern?',
        
        // Settings
        account: 'Konto',
        privacy: 'Datenschutz',
        security: 'Sicherheit',
        accountInfo: 'Kontoinformationen',
        username: 'Benutzername',
        role: 'Rolle',
        preferences: 'Einstellungen',
        language: 'Sprache',
        selectLanguage: 'Wählen Sie Ihre bevorzugte Sprache',
        english: 'Englisch',
        german: 'Deutsch',
        myanmar: 'Myanmar (မြန်မာ)',
        timeZone: 'Zeitzone',
        syncTimeZone: 'Mit lokaler Zeit synchronisieren',
        themeMode: 'Design-Modus',
        chooseAppearance: 'Wählen Sie Ihr bevorzugtes Erscheinungsbild',
        light: 'Hell',
        dark: 'Dunkel',
        system: 'System',
        systemModeInfo: 'Systemmodus passt sich Ihren Geräteeinstellungen an',
        locationServices: 'Standortdienste',
        locationEnabled: 'Aktiviert - Verfolgt Ihren Standort',
        locationDisabled: 'Deaktiviert - Standortzugriff blockiert',
        helpSupport: 'Hilfe & Support',
        
        // Directory
        addContact: 'Kontakt hinzufügen',
        searchContacts: 'Namen, Rollen, Stadt suchen...',
        all: 'Alle',
        admin: 'Administrator',
        emergency: 'Notfall',
        share: 'Teilen',
        download: 'vCard herunterladen',
        print: 'Drucken',
        generateQR: 'QR-Code erstellen',
        delete: 'Löschen',
        noContactsFound: 'Keine Kontakte gefunden',
        tryAdjusting: 'Versuchen Sie, Ihre Suche oder Filter anzupassen',
        contactInfo: 'Kontaktinformationen',
        callSign: 'Rufzeichen',
        addNewContact: 'Neuen Kontakt hinzufügen',
        required: 'erforderlich',
        enterFullName: 'Vollständigen Namen eingeben',
        enterRole: 'z.B. Ersthelfer, Koordinator',
        enterCallSign: 'z.B. Alpha-1, Bravo-2',
        enterEmail: 'email@beispiel.de',
        enterPhone: '+49-555-0123',
        userType: 'Typ',
        user: 'Benutzer',
        responder: 'Einsatzkraft',
        fillRequired: 'Bitte füllen Sie alle Pflichtfelder aus (Name, E-Mail, Telefon)',
        
        // Chat
        newMessage: 'Neue Nachricht',
        typeMessage: 'Nachricht eingeben...',
        send: 'Senden',
        encryptedConversation: 'Ende-zu-Ende verschlüsseltes Gespräch',
        attachments: 'Anhänge',
        image: 'Bild',
        document: 'Dokument',
        voiceMessage: 'Sprachnachricht',
        videoCall: 'Videoanruf',
        liveLocation: 'Live-Standort',
        
        // System Status
        systemStatus: 'Systemstatus',
        operationalStatus: 'Betriebsstatus',
        alerts: 'Aktive Alarme',
        gpsSignal: 'GPS-Signal',
        userStatus: 'Benutzerstatus',
        lastUpdated: 'Zuletzt aktualisiert',
        safe: 'Sicher',
        searching: 'Suchen',
        close: 'Schließen',
        
        // Notifications
        totalNotifications: 'Gesamt',
        unread: 'Ungelesen',
        read: 'Gelesen',
        markAllRead: 'Alle als gelesen markieren',
        
        // Common
        loading: 'Wird geladen...',
        error: 'Fehler',
        success: 'Erfolg',
        confirm: 'Bestätigen',
        back: 'Zurück',
        nextButton: 'Weiter',
        finish: 'Fertig',
        yes: 'Ja',
        no: 'Nein',
        ok: 'OK',

        // Emergency / SOS
        imSafe: 'Ich bin sicher',
        safeStatusUpdated: 'Ihr Status wurde aktualisiert und mit Einsatzkräften geteilt.',
        returnToDashboard: 'Zurück zum Dashboard',
        sosActivated: 'SOS AKTIVIERT',
        emergencyNotified: 'Rettungsdienste wurden über Ihren Standort informiert.',
        broadcastingSignal: 'Signal wird gesendet...',
        gettingLocation: 'Live-Standort wird ermittelt...',
        locationUnavailable: 'Standort nicht verfügbar (GPS aktivieren)',
        cancelAlert: 'Alarm abbrechen',
        emergencyResponse: 'Notfall-Reaktion',
        shareStatusReport: 'Teilen Sie Ihren Status oder melden Sie einen Vorfall.',
        respondersNotified: 'Einsatzkräfte werden benachrichtigt.',
        sosHelp: 'SOS / Hilfe',
        reportAnIncident: 'Vorfall melden',
        floodPlacementHint: 'Der Yangon-Flusskorridor hat Häuser entlang der Ufer, Hafenbereiche und Insel-Siedlungen. Platzieren Sie Hochwasser-Vorfälle an Flussstandorten, an denen Gemeinden gefährdet sind. Nutzen Sie die Karte unten für den genauen Punkt.',
        reviewReport: 'Bericht prüfen',
        feed: 'Feed',
        history: 'Verlauf',
        mySubmissions: 'Meine Meldungen',
        noReportsSubmitted: 'Noch keine Meldungen eingereicht.',
        completePreparednessKit: 'Notfallausrüstung vervollständigen',
        updateMedicalProfile: 'Medizinprofil aktualisieren',
        joinDrillSession: 'An einer Übung teilnehmen',
        fullyPreparedMessage: 'Sie sind vollständig vorbereitet! Gute Arbeit.',
        closeBreakdown: 'Schließen',
        highZone: 'Hoch 76–100',
        midZone: 'Mittel 41–75',
        lowZone: 'Niedrig 0–40',
        preparedness: 'Vorsorge',
        deleteChecklistConfirm: 'Diesen Eintrag löschen?',
        deleteDrillConfirm: 'Diese Übung löschen?',
        checklist: 'Checkliste',
        drills: 'Übungen',
        profileSettings: 'Profileinstellungen',
        appPreferences: 'App-Einstellungen',
        notificationSettings: 'Benachrichtigungseinstellungen',
        emergencyPlan: 'Notfallplan',
        shareApp: 'App teilen',
        signOutConfirm: 'Möchten Sie sich wirklich abmelden?',
        highSeverity: 'Hohe Schwere',
        moderateSeverity: 'Mäßige Schwere',
        lowSeverity: 'Geringe Schwere',
        criticalSeverity: 'Kritische Schwere',
        drillsAndLogs: 'Übungen & Protokolle',
        checklistProgress: 'Checklisten-Fortschritt',
        adminMode: 'Admin-Modus',
        upcomingDrills: 'Geplante Übungen',
        pastLogs: 'Vergangene Protokolle',
        editItem: 'Eintrag bearbeiten',
        newChecklistItem: 'Neuer Checklisten-Eintrag',
        editDrill: 'Übung bearbeiten',
        newDrillSession: 'Neue Übung',
        newTutorialItem: 'Neues Tutorial',
        editTutorial: 'Tutorial bearbeiten',
        newLearnItem: 'Neuer Lern-Eintrag',
        editLearnItem: 'Lern-Eintrag bearbeiten',
        learnItemType: 'Typ',
        learnItems: 'Lern-Einträge',
        noLearnItems: 'Noch keine Lern-Einträge.',
        deleteLearnItemConfirm: 'Diesen Lern-Eintrag löschen?',
        deleteTutorialConfirm: 'Dieses Tutorial löschen?',
        noChecklistItems: 'Keine Checklisten-Einträge.',
        noUpcomingDrills: 'Keine geplanten Übungen.',
        noPastLogs: 'Noch keine vergangenen Protokolle.',
        noNotesRecorded: 'Keine Notizen erfasst.',
        participants: 'Teilnehmer',
        register: 'Registrieren',
        title: 'Titel',
        xpPointsLabel: 'XP-Punkte',
        privacyPolicy: 'Datenschutzrichtlinie',
        privacyControls: 'Datenschutzeinstellungen',
        complete: 'Abgeschlossen',
        adminPanel: 'Admin-Bereich',
        date: 'Datum',
        dateLabel: 'Datum',
        notSet: 'Nicht festgelegt',
        pushNotifications: 'Push-Benachrichtigungen',
        emailNotifications: 'E-Mail-Benachrichtigungen',
        profileVisibility: 'Profil-Sichtbarkeit',
        shareLocation: 'Standort teilen',
        deleteAccount: 'Konto löschen',
        // System Status
        systemOperational: 'System betriebsbereit',
        allSystemsNormal: 'Alle Systeme funktionieren normal.',
        criticalNotifications: 'Kritische Benachrichtigungen',
        yourStatus: 'Ihr Status',
        currentSafetyStatus: 'Aktueller Sicherheitsstatus',
        network: 'Netzwerk',
        // Chat
        emergencyResponseTeam: 'Notfall-Team',
        communitySafetyGroup: 'Community-Sicherheitsgruppe',
        adminSupport: 'Admin-Support',
        localResponders: 'Lokale Einsatzkräfte',
        aiSafetyAssistant: 'KI-Sicherheitsassistent',
        aiTyping: 'KI tippt...',
        aiUnavailableFallback: 'Menschenliche Einsatzkräfte sind offline. Der KI-Assistent ist 24/7 für Sicherheitsberatung verfügbar.',
        urgentHelp: 'Dringende Hilfe',
        sosSigns: 'SOS-Zeichen',
        emojiUrgentHelp: 'Dringende Hilfe',
        emojiEmergency: 'Notfall',
        emojiWarning: 'Warnung',
        emojiMedical: 'Medizinisch',
        emojiFire: 'Feuer',
        emojiFlood: 'Überschwemmung',
        emojiEarthquake: 'Erdbeben',
        emojiOk: 'OK',
        emojiShelter: 'Unterkunft',
        emojiNoElectricity: 'Kein Strom',
        emojiNoInternet: 'Kein Internet',
        emojiWounded: 'Verletzt',
        emojiCannotSpeak: 'Kann nicht sprechen',
        emojiTrapped: 'Eingeschlossen',
        emojiNeedWater: 'Brauche Wasser',
        emojiNeedFood: 'Brauche Essen',
        emojiSilent: 'Leise (Ruhe)',
        emojiChemical: 'Chemische Gefahr',
        emojiPoison: 'Gift',
        emojiShooterActive: 'Bewaffneter Täter',
        // Profile sections
        activityStatistics: 'Aktivitätsstatistiken',
        skillsAndCertifications: 'Fähigkeiten & Zertifikate',
        suggestedSkills: 'Empfohlene Fähigkeiten',
        experiencePoints: 'Erfahrungspunkte',
        volunteerPoints: 'Freiwilligenpunkte',
        levelProgress: 'Stufenfortschritt',
        nextLevel: 'Nächste Stufe',
        fullName: 'Vollständiger Name',
        add: 'Hinzufügen',
        noSkillsAdded: 'Noch keine Fähigkeiten hinzugefügt',
        addFirstSkill: 'Erste Fähigkeit hinzufügen',
        firstAid: 'Erste Hilfe',
        cprCertified: 'HLW zertifiziert',
        fireSafety: 'Brandschutz',
        emergencyResponseSkill: 'Notfall-Reaktion',
        searchAndRescue: 'Such- und Rettungseinsatz',
        emergencyKitAchievement: 'Notfallausrüstung',
        firstAidTrained: 'Erste-Hilfe geschult',
        homeSafety: 'Heimische Sicherheit',
        certified: 'Zertifiziert',
        // Checklist items
        checklistBuildKit: 'Basis-Notfallausrüstung zusammenstellen',
        checklistSaveNumbers: 'Lokale Notfallnummern speichern',
        checklistStoreWater: '3 Tage Wasser lagern (1 gal/Person/Tag)',
        checklistStockFood: '3 Tage haltbare Lebensmittel einlagern',
        checklistCanOpener: 'Handdosenöffner',
        checklistRadio: 'Batterie- oder Kurbelradio',
        checklistFlashlight: 'Taschenlampe + Ersatzbatterien',
        checklistWhistle: 'Pfeife zum Signalisieren',
        checklistWrench: 'Schraubenschlüssel/Zange für Versorgung',
        checklistLocalMaps: 'Lokale Karten (Papier)',
        checklistMedications: 'Verschreibungspflichtige Medikamente (7 Tage)',
        checklistDustMask: 'Staubmaske (N95)',
        checklistTowelettes: 'Feuchttücher/Müllsäcke',
        checklistInsurance: 'Kopien der Versicherungspolicen',
        checklistIdRecords: 'Ausweise und Bankunterlagen',
        checklistCash: 'Bargeld für Notfälle',
        checklistSecureFurniture: 'Schwere Möbel (Regale, Schränke) an Wände sichern',
        checklistDropCoverHold: 'Drop-Cover-Hold-Übung mit Haushalt üben',
        checklistGasShutoff: 'Standort des Gasabsperrventils kennen',
        checklistSturdyShoes: 'Robuste Schuhe am Bett bereithalten (bei Scherben)',
        checklistTsunamiRoute: 'Evakuierungsroute zu höherem Gelände kennen',
        checklistTsunamiZone: 'Tsunami-Gefahrenzone und sicheren Treffpunkt identifizieren',
        checklistGoBag: 'Go-Bag für schnelle Evakuierung bereithalten',
        checklistSecureOutdoor: 'Außenbereiche vor Sturm sichern oder verstauen',
        checklistStormShelter: 'Nächstes Sturmunterkunft kennen',
        checklistChargeDevices: 'Alle Geräte vor Sturm aufladen',
        checklistSmokeDetectors: 'Rauchmelder installieren und testen',
        checklistFireExtinguisher: 'Feuerlöscher in Küche und nahe Ausgängen',
        checklistEscapePlan: 'Fluchtplan mit 2 Ausgängen pro Raum',
        checklistMeetingPoint: 'Treffpunkt im Freien für Haushalt festlegen',
        // Drills
        drillAnnualFire: 'Jährliche Brandübung',
        drillEarthquake: 'Erdbeben-Simulation',
        drillActiveShooter: 'Amoklauf-Übung',
        evacuation: 'Evakuierung',
        lockdown: 'Sicherheitssperre',
        // Learn / Tutorials
        learn: 'Lernen',
        learnSubtitle: 'Anleitungen, Tutorials & Ressourcen',
        howToGuides: 'So nutzen Sie SafeSphere',
        readMore: 'Weitere Infos',
        tutorialVideos: 'Tutorial-Videos & Anleitungen',
        externalResources: 'Externe Ressourcen',
        learnMore: 'Tutorials & Ressourcen ansehen',
        learnReportIncident: 'Vorfall melden',
        learnReportIncidentDesc: 'Tippen Sie auf SOS oder Vorfall melden, um Ihren Standort und Ihre Situation an Einsatzkräfte zu teilen. Fügen Sie Fotos und Details für schnellere Hilfe hinzu.',
        learnChecklist: 'Checkliste abschließen',
        learnChecklistDesc: 'Bauen Sie Ihr Notfall-Set Schritt für Schritt auf. Markieren Sie erledigte Punkte, um Ihren Sicherheits-Score und Erfolge zu verbessern.',
        learnLiveMap: 'Live Command Map nutzen',
        learnLiveMapDesc: 'Sehen Sie Vorfälle, Ressourcen und Einsatzkräfte auf der Karte. Tippen Sie auf Marker für Details. Aktivieren Sie den Standort für Echtzeit-Navigation.',
        learnChat: 'Mit Einsatzkräften chatten',
        learnChatDesc: 'Verschlüsselte Nachrichten senden, Live-Standort teilen oder Videoanruf starten. Nutzen Sie SOS-Emojis für schnelle Status-Updates.',
        tutorialEmergencyBasics: 'Grundlagen der Notfallvorsorge',
        tutorialEmergencyBasicsDesc: 'So bereiten Sie Zuhause und Familie auf Notfälle vor.',
        tutorialDisasterPrep: 'Katastrophenvorsorge',
        tutorialDisasterPrepDesc: 'Set bauen, Plan erstellen, informiert bleiben.',
        resourceRedCross: 'Notfallvorsorge & Erste Hilfe',
        resourceFEMA: 'Bundes-Notfallmanagement',
        resourceWHO: 'Globale Gesundheitsnotfälle',
        resourceCDC: 'Öffentliche Gesundheitsnotfälle',
        achFirstDrill: 'Erste Übung',
        achProfile: 'Profil',
        achKit: 'Set bereit',
        achExpert: 'Experte',
        onboardingWelcome: 'Willkommen bei SafeSphere',
        onboardingWelcomeDesc: 'Bleiben Sie auf Notfälle vorbereitet. Bauen Sie Ihr Set, absolvieren Sie Übungen und lernen Sie lebensrettende Fähigkeiten.',
        onboardingPrepare: 'Vorbereiten',
        onboardingPrepareDesc: 'Nutzen Sie die Checkliste für Ihr Notfall-Set, nehmen Sie an Übungen teil und verdienen Sie XP.',
        onboardingLearn: 'Lernen',
        onboardingLearnDesc: 'Sehen Sie Tutorials und nutzen Sie Ressourcen. Besuchen Sie den Bereich Lernen für Anleitungen, Videos und Tipps.',
        onboardingReady: 'Sie sind bereit!',
        onboardingReadyDesc: 'Beginnen Sie mit der Checkliste unten, absolvieren Sie Übungen und erkunden Sie Tutorials. Bleiben Sie sicher!',
        onboardingGetStarted: "Los geht's",
        onboardingViewLearn: 'Lernen & Tutorials ansehen',
        onboardingSkip: 'Überspringen',
        // Tutorials
        tutorials: 'Tutorials',
        learnAndEarn: 'Lernen Sie aus Videos und verdienen Sie XP.',
        watchTutorial: 'Ansehen',
        markComplete: 'Als erledigt markieren',
        completed: 'Erledigt',
        earnXp: '{xp} XP verdienen',
        noTutorials: 'Keine Tutorials verfügbar.',
        tutorialEarthquake: 'Erdbeben-Sicherheits-Videoserie',
        tutorialEarthquakeDesc: 'So bereiten Sie sich auf Erdbeben vor und bleiben sicher.',
        tutorialFirstAid: 'Erste-Hilfe-Grundlagen',
        tutorialFirstAidDesc: 'Wichtige Erste-Hilfe-Fähigkeiten für Notfälle.',
        tutorialTrauma: 'Traumaberatung',
        tutorialTraumaDesc: 'Jemandem bei Hyperventilation während einer Panikattacke helfen.',
        tutorialCpr: 'CPR & Defibrillator',
        tutorialCprDesc: 'So führen Sie eine CPR durch und verwenden einen AED.',
        tutorialEvac: 'Notfall-Evakuierung',
        tutorialEvacDesc: 'Red-Cross-Ready: 3 Schritte zur Vorbereitung.',
        // Privacy Policy
        yourPrivacyMatters: 'Ihre Privatsphäre zählt',
        euDataProtection: 'DSGVO-konform',
        privacyIntro: 'SafeSphere verpflichtet sich, Ihre personenbezogenen Daten gemäß EU-DSGVO und internationalen Datenschutzstandards zu schützen.',
        dataCollection: '1. Datenerhebung',
        dataCollectionDesc: 'Wir erfassen Standortdaten für Notfallrouting und Sicherheitswarnungen. Diese Daten sind verschlüsselt und werden nur mit Einsatzkräften geteilt, wenn Sie explizit SOS auslösen oder einen Bericht einreichen.',
        locationNeverSold: 'Ihr Standort wird niemals an Dritte verkauft oder für Werbezwecke genutzt.',
        endToEndEncryption: '2. Ende-zu-Ende-Verschlüsselung',
        endToEndEncryptionDesc: 'Alle Teammeldungen sind Ende-zu-Ende verschlüsselt. Wir können Ihre Nachrichten nicht lesen oder Ihre Anrufe hören. Verschlüsselungsschlüssel werden lokal auf Ihrem Gerät gespeichert.',
        aesEncryption: 'AES-Verschlüsselung',
        zeroAccessPolicy: 'Zero-Access-Richtlinie',
        userRights: '3. Nutzerrechte',
        userRightsDesc: 'Sie haben das Recht, jederzeit über das Einstellungsmenü oder per Support-Anfrage auf Ihre personenbezogenen Daten zuzugreifen, sie zu korrigieren oder zu löschen.',
        rightToAccess: 'Recht auf Zugang zu Ihren Daten',
        rightToRectification: 'Recht auf Berichtigung',
        rightToErasure: 'Recht auf Löschung (Recht auf Vergessenwerden)',
        rightToPortability: 'Recht auf Datenübertragbarkeit',
        emergencyDisclosure: '4. Notfallweitergabe',
        emergencyDisclosureDesc: 'Bei lebensbedrohlichen Situationen können wir Ihren letzten bekannten Standort mit verifizierten Rettungsdiensten (Polizei, Feuerwehr, Rettung) teilen, um Rettungseinsätze zu unterstützen.',
        whenWeShareData: 'Wann wir Ihre Daten teilen:',
        triggerSos: 'Sie lösen einen SOS-Alarm aus',
        emergencyRequest: 'Rettungsdienste fordern Standortunterstützung an',
        legalObligation: 'Rechtliche Verpflichtung zur Schadensverhütung',
        questionsOrConcerns: 'Fragen oder Bedenken?',
        privacyContact: 'Bei Fragen zu dieser Datenschutzrichtlinie oder zur Datenverarbeitung wenden Sie sich an unseren Datenschutzbeauftragten:',
        allRightsReserved: 'Alle Rechte vorbehalten.',
        euGdprCompliant: 'DSGVO-konform',
        isoCertified: 'ISO 27001 zertifiziert',
        helpAndSupport: 'Hilfe & Support',
        helpSupportTitle: 'SafeSphere Hilfe & Support',
        emailSupport: 'E-Mail-Support',
        responseTime: 'Antwortzeit: 2-4 Stunden',
        emergencyHotline: 'Notfall-Hotline',
        liveChat: 'Live-Chat',
        liveChatDesc: '24/7 in der App verfügbar',
        helpCenter: 'Hilfezentrum',
        technicalSupport: 'Technischer Support',
        emergencyCallNote: 'Bei lebensbedrohlichen Notfällen rufen Sie sofort Ihre lokalen Rettungsdienste an (112, 122, 133, 144, 911, etc.).',
        // Settings - Notifications & more
        alertPreferences: 'Alarm-Einstellungen',
        deliveryMethods: 'Übermittlungsmethoden',
        emergencyAlertsLabel: 'Notfallalarme',
        reportUpdates: 'Berichtsaktualisierungen',
        systemMessages: 'Systemnachrichten',
        statusChanges: 'Statusänderungen',
        appUpdates: 'App-Updates',
        instantMobileAlerts: 'Sofortige Mobil-Benachrichtigungen',
        offlineModeFeatures: 'Offline-Modus-Funktionen',
        offlineFeaturesDesc: 'Aktivieren Sie Funktionen, die ohne Internetverbindung funktionieren, damit Sie auch offline Retter signalisieren können.',
        whyOfflineFeaturesMatter: 'Warum Offline-Funktionen wichtig sind',
        offlineFeaturesBullets: 'Bei Notfällen kann das Internet ausgefallen sein. Diese Funktionen ermöglichen Ihnen:',
        bluetoothBeacon: 'Bluetooth-Bake',
        broadcastSosBluetooth: 'SOS per Bluetooth senden',
        gpsLocation: 'GPS-Standort',
        trackLocationOffline: 'Standort offline verfolgen',
        offlineMode: 'Offline-Modus',
        workWithoutInternet: 'Ohne Internet arbeiten',
        localStorageSync: 'Lokale Speicher-Synchronisation',
        cacheDataLocally: 'Daten lokal zwischenspeichern',
        emergencyBeacon: 'Notfall-Bake',
        sendSosWithoutInternet: 'SOS ohne Internet senden',
        dataManagement: 'Datenverwaltung',
        downloadMyData: 'Meine Daten herunterladen',
        clearCache: 'Cache leeren',
        clearCacheConfirm: 'Alle gecachten Daten löschen? Ihr Profil und Einstellungen bleiben erhalten.',
        deleteAccountConfirm: 'Konto und alle Daten löschen? Dies kann nicht rückgängig gemacht werden. Sie werden abgemeldet.',
        passwordAndAuthentication: 'Passwort & Authentifizierung',
        changePassword: 'Passwort ändern',
        currentPassword: 'Aktuelles Passwort',
        newPassword: 'Neues Passwort',
        confirmNewPassword: 'Neues Passwort bestätigen',
        updatePassword: 'Passwort aktualisieren',
        passwordChangedSuccess: 'Passwort erfolgreich geändert!',
        twoFactorAuthentication: 'Zwei-Faktor-Authentifizierung',
        extraSecurityLayer: 'Zusätzliche Sicherheitsebene',
        twoFactorDesc: 'Fügen Sie eine zusätzliche Sicherheitsebene hinzu, indem Sie bei der Anmeldung einen Bestätigungscode verlangen.',
        enable2fa: '2FA aktivieren',
        enableFaceId: 'Face ID aktivieren',
        twoFactorFaceIdRequirement: 'Aktivieren Sie sowohl 2FA als auch Face ID zur Authentifizierung.',
        faceId: 'Face ID',
        faceIdRequirementError: 'Bitte aktivieren Sie 2FA und Face ID in Einstellungen > Sicherheit für die Face-ID-Authentifizierung.',
        activeSessions: 'Aktive Sitzungen',
        currentSession: 'Aktuelle Sitzung',
        lastActive: 'Zuletzt aktiv',
        endAllOtherSessions: 'Alle anderen Sitzungen beenden',
        endAllOtherSessionsConfirm: 'Alle anderen Sitzungen beenden? Sie bleiben auf diesem Gerät angemeldet.',
        otherDevices: 'Andere Geräte',
        active: 'Aktiv',
        disablingLocationWarning: 'Das Deaktivieren der Standortdienste kann Notfallfunktionen und Sicherheitswarnungen einschränken.',
        locationDataEncrypted: 'Standortdaten sind verschlüsselt und werden nur in Notfällen geteilt. Wir respektieren Ihre Privatsphäre.',
        syncReportsWhenOnline: 'Berichte zur Synchronisation in die Warteschlange stellen, wenn online',
        offlineBullet1: 'Notsignale per Bluetooth an nahe Geräte senden',
        offlineBullet2: 'GPS-Standort teilen, wenn die Verbindung wieder besteht',
        offlineBullet3: 'Gecachte Notfallressourcen offline nutzen',
        // Command Center
        commandCenter: 'Einsatzzentrale',
        incidents: 'Vorfälle',
        logistics: 'Logistik',
        triage: 'Triage',
        team: 'Team',
        safetyMap: 'Sicherheitskarte',
        // QR Scanner
        qrScanner: 'QR-Scanner',
        scanSafesphereQrCodes: 'SafeSphere QR-Codes scannen',
        rescueCenterFound: 'Rettungszentrum gefunden!',
        nearestEmergencyFacilityScanned: 'Nächstgelegenes Notfallzentrum gescannt',
        qrCodeId: 'QR-Code-ID:',
        scanAgain: 'Erneut scannen',
        callNow: 'Jetzt anrufen',
        scanning: 'Scannen...',
        positionQrInFrame: 'QR-Code in den Rahmen positionieren',
        phoneNumberCopied: 'Telefonnummer in die Zwischenablage kopiert!',
        // Auth notifications
        signInSuccess: 'Sie haben sich erfolgreich angemeldet.',
        loggedOutSuccess: 'Sie wurden erfolgreich abgemeldet!',
        signOutConfirmShort: 'Möchten Sie sich wirklich abmelden?',
        // Generic confirm & success
        areYouSure: 'Sind Sie sicher!',
        savedSuccessfully: 'Erfolgreich gespeichert!',
        deletedSuccessfully: 'Erfolgreich gelöscht.',
        deleteItemConfirm: 'Möchten Sie diesen Eintrag wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
        permissionDenied: 'Zugriff verweigert',
        permissionDeniedAdmin: 'Zugriff verweigert: Nur Admins können Einträge löschen.',
        markResolvedArchive: 'Als erledigt markieren und archivieren?',
        scanQrCode: 'QR-Code scannen',
        // Command Center - Incidents, Logistics, Triage, Team
        inventoryLog: 'Inventarprotokoll',
        triageBoard: 'Triage-Board',
        teamMembers: 'Teammitglieder',
        searchIncidents: 'Vorfälle suchen...',
        statusAll: 'Status: Alle',
        typeAll: 'Typ: Alle',
        newItem: 'Neuer Eintrag',
        noReportsFound: 'Keine Berichte in dieser Ansicht gefunden.',
        // Safety Map Editor
        view: 'Ansehen',
        addPoint: 'Punkt hinzufügen',
        drawPath: 'Pfad zeichnen',
        evacRoute: 'Evakuierungsroute',
        transportRoad: 'Transportstraße',
        clear: 'Löschen',
        tapMapToPlace: 'Karte antippen zum Platzieren von',
        tapMapToDraw: 'Karte antippen zum Zeichnen des',
        pathLabel: 'Pfads',
        newAssetDetails: 'Neue Anlagen-Details',
        editAsset: 'Anlage bearbeiten',
        labelName: 'Bezeichnung / Name',
        mainExitPlaceholder: 'z.B. Hauptausgang',
        optionalDetailsPlaceholder: 'Optionale Angaben...',
        exit: 'Ausgang',
        meetingPoint: 'Sammelpunkt',
        extinguisher: 'Feuerlöscher',
        hydrant: 'Hydrant',
        // Alert & incident descriptions
        heavyRainExpected: 'Starkregen erwartet. Meiden Sie tiefer gelegene Gebiete.',
        stayHydrated: 'Bleiben Sie hydratisiert und meiden Sie direkte Sonne.',
        floodType: 'HOCHWASSER',
        fireType: 'BRAND',
        streetFloodedNearPark: 'Straße in der Nähe des Parks überflutet',
        smallBrushFireSpotted: 'Kleiner Buschbrand gesichtet',
    },
    my: {
        // Navigation
        home: 'အိမ်',
        map: 'မြေပုံ',
        prepare: 'ပြင်ဆင်မှု',
        sos: 'အရေးပေါ်',
        chat: 'ချက်',
        menu: 'မီနူး',
        // Header & Menu
        myProfile: 'ကျွန်ုပ်၏ ပရိုဖိုင်',
        settings: 'ဆက်တင်များ',
        signOut: 'ထွက်မည်',
        messages: 'မက်ဆေ့ချ်များ',
        notifications: 'အကြောင်းကြားချက်များ',
        directory: 'လူအမည်စာရင်း',
        // Home Page
        goodMorning: 'ကောင်းသောနံနက်ခင်းပါ',
        goodAfternoon: 'ကောင်းသောမွန်းတည့်ချိန်ပါ',
        goodEvening: 'ကောင်းသောညနေခင်းပါ',
        status: 'အခြေအနေ',
        monitoring: 'စောင့်ကြည့်ခြင်း',
        checkStatus: 'အခြေအနေစစ်ဆေးပါ',
        viewKit: 'အရန်ပစ္စည်းကြည့်ပါ',
        activeAlerts: 'လက်ရှိသတိပေးချက်များ',
        liveData: 'လက်ရှိဒေတာ',
        viewAll: 'အားလုံးကြည့်ပါ',
        quickActions: 'အမြန်လုပ်ဆောင်ချက်များ',
        reportIncident: 'ဖြစ်ရပ်မှတ်တမ်းတင်ပါ',
        emergencyContacts: 'အရေးပေါ်ဆက်သွယ်မှုများ',
        safetyTips: 'ဘေးကင်းလုံခြုံမှုအကြံပြုချက်များ',
        nearbyResources: 'အနီးဆုံးအရင်းအမြစ်များ',
        flashFloodWarning: 'ရုတ်တရက်ရေကြီးခြင်း သတိပေးချက်',
        heatwaveAdvisory: 'ပူပြင်းမှုသတိပေးချက်',
        noActiveAlerts: 'လက်ရှိသတိပေးချက်မရှိပါ။ ဘေးကင်းစွာနေပါ။',
        offline: 'အင်တာနက်မရှိ',
        score: 'ရမှတ်',
        level: 'အဆင့်',
        beginner: 'စတင်သူ',
        awareCitizen: 'သတိရှိပြည်သူ',
        safetyExpert: 'ဘေးကင်းလုံခြုံမှုကျွမ်းကျင်သူ',
        fullyPrepared: 'သင့်အား အပြည့်အဝပြင်ဆင်ပြီးပါပြီ။',
        joinSafetyDrill: 'ဘေးကင်းလုံခြုံမှုလေ့ကျင့်ခန်းတွင် ပါဝင်ပါ',
        completeProfile: 'ပရိုဖိုင်အချက်အလက်ပြီးမြောက်ပါ',
        completeEmergencyKit: 'အရေးပေါ်အရန်ပစ္စည်းပြီးမြောက်ပါ',
        nextAction: 'နောက်တစ်ဆင့်',
        kitReadiness: 'အရန်ပစ္စည်းအဆင်သင့်ဖြစ်မှု',
        profileComplete: 'ပရိုဖိုင်ပြီးမြောက်ပြီ',
        drillParticipation: 'လေ့ကျင့်ခန်းပါဝင်မှု',
        readinessScore: 'အဆင်သင့်ဖြစ်မှုရမှတ်',
        emergencyKit: 'အရေးပေါ်အရန်ပစ္စည်း',
        profileSetup: 'ပရိုဖိုင်ထည့်သွင်းခြင်း',
        drillTraining: 'လေ့ကျင့်ခန်းသင်ကြားခြင်း',
        nextLabel: 'နောက်တစ်ဆင့်။',
        scoreBreakdown: 'ရမှတ်ခွဲခြမ်းခြင်း',
        viewScoreBreakdown: 'ရမှတ်ခွဲခြမ်းခြင်းကြည့်ပါ',
        total: 'စုစုပေါင်း',
        kitReadinessTitle: 'အရန်ပစ္စည်းအဆင်သင့်ဖြစ်မှု',
        emergencySuppliesPlans: 'အရေးပေါ်ပစ္စည်းများနှင့် အစီအစဉ်များ',
        profileCompletenessTitle: 'ပရိုဖိုင်ပြီးမြောက်မှု',
        medicalContactDetails: 'ဆေးဘက်ဆိုင်ရာနှင့် ဆက်သွယ်မှုအချက်အလက်များ',
        practiceSimulations: 'လေ့ကျင့်ခန်းစမ်းသပ်ခြင်းများ',
        broadcast: 'ထုတ်လွှင့်ခြင်း',
        broadcastAlert: 'သတိပေးချက်ထုတ်လွှင့်ပါ',
        alertTitle: 'သတိပေးချက်ခေါင်းစဉ်',
        alertTitlePlaceholder: 'ဥပမာ ရုတ်တရက်ရေကြီးခြင်း သတိပေးချက်',
        severity: 'ပြင်းထန်မှု',
        low: 'နိမ့်',
        moderate: 'အလယ်အလတ်',
        high: 'မြင့်',
        alertType: 'အမျိုးအစား',
        general: 'အထွေထွေ',
        flood: 'ရေကြီးခြင်း',
        fire: 'မီးလောင်ခြင်း',
        earthquake: 'ငလျင်လှုပ်ခြင်း',
        storm: 'မိုးသက်လေပြင်းကျခြင်း',
        description: 'ဖော်ပြချက်',
        descriptionPlaceholder: 'ပြည်သူများအတွက် ညွှန်ကြားချက်များ...',
        sendAlert: 'သတိပေးချက်ပို့ပါ',
        incidentFrequencyLast6h: 'ဖြစ်ရပ်ကြိမ်နှုန်း (ပြီးခဲ့သည့် ၆ နာရီ)',
        incidentFrequencyLast8h: 'ဖြစ်ရပ်ကြိမ်နှုန်း (ပြီးခဲ့သည့် ၈ နာရီ)',
        incidentFrequencyLast24h: 'ဖြစ်ရပ်ကြိမ်နှုန်း (ပြီးခဲ့သည့် ၂၄ နာရီ)',
        incidentFrequencyByWeek: 'အပတ်အလိုက် ဖြစ်ရပ်ကြိမ်နှုန်း',
        incidentFrequencyByDay: 'နေ့အလိုက် ဖြစ်ရပ်ကြိမ်နှုန်း',
        incidentFrequencyByMonth: 'လအလိုက် ဖြစ်ရပ်ကြိမ်နှုန်း',
        incidentFrequencyByYear: 'နှစ်အလိုက် ဖြစ်ရပ်ကြိမ်နှုန်း',
        incidentFrequencyLast1Month: 'ပြီးခဲ့သည့် ၁ လ',
        incidentFrequencyLast1Year: 'ပြီးခဲ့သည့် ၁ နှစ်',
        seismicAlerts: 'ငလျင်သတိပေးချက်များ',
        viewOnMap: 'မြေပုံတွင်ကြည့်ပါ',
        clickToViewLocation: 'မြေပုံတွင် တည်နေရာကြည့်ရန် နှိပ်ပါ',
        severityLegendHint: 'ပြင်းထန်မှုအတွက် Y ဝင်ရိုးပေါ်တွင် မောင်းထားပါ။ မြေပုံတွင် တည်နေရာကြည့်ရန် ဒေတာနှိပ်ပါ။',
        liveCoordinates: 'လက်ရှိပြ ကိုဩဒီနိတ်များ',
        weather: 'ရာသီဥတု',
        weatherUnavailable: 'မရနိုင်ပါ',
        syncLiveData: 'လက်ရှိပြ ကိုဩဒီနိတ်နှင့် ရာသီဥတု ချိန်ကိုက်ပါ',
        // Profile
        personalInfo: 'ကိုယ်ရေးအချက်အလက်',
        edit: 'ပြင်ဆင်ပါ',
        save: 'သိမ်းပါ',
        cancel: 'ပယ်ဖျက်ပါ',
        name: 'အမည်',
        email: 'အီးမေးလ်',
        phone: 'ဖုန်း',
        bloodType: 'သွေးအမျိုးအစား',
        emergencyContact: 'အရေးပေါ်ဆက်သွယ်မှု',
        safetyScore: 'ဘေးကင်းလုံခြုံမှုရမှတ်',
        xpPoints: 'XP မှတ်များ',
        volunteer: 'စေတနာ့ဝန်ထမ်း',
        profile: 'ပရိုဖိုင်',
        stats: 'စာရင်းအင်း',
        skills: 'ကျွမ်းကျင်မှုများ',
        achievements: 'ဘေးဒ္ခပြင်ဆင်မှု အောင်မြင်မှုများ',
        recentActivities: 'လက်ရှိလုပ်ဆောင်ချက်များ',
        uploadImage: 'ပုံအပ်လုဒ်/ပြောင်းပါ',
        deleteImage: 'ပုံဖျက်ပါ',
        confirmProfilePicture: 'ပရိုဖိုင်ပုံအတည်ပြုပါ',
        saveProfilePictureQuestion: 'ဤပုံကို သင့်ပရိုဖိုင်ပုံအဖြစ် သိမ်းထားလိုပါသလား။',
        // Settings
        account: 'အကောင့်',
        privacy: 'ကိုယ်ရေးအချက်အလက် လုံခြုံမှု',
        security: 'လုံခြုံရေး',
        accountInfo: 'အကောင့်အချက်အလက်',
        username: 'အသုံးပြုသူအမည်',
        role: 'အခန်းကဏ္ဍ',
        preferences: 'ရွေးချယ်မှု',
        language: 'ဘာသာစကား',
        selectLanguage: 'သင့်ရွေးချယ်ထားသော ဘာသာစကားရွေးပါ',
        english: 'အင်္ဂလိပ်',
        german: 'ဂျာမန်',
        myanmar: 'မြန်မာ',
        timeZone: 'အချိန်ဇုန်',
        syncTimeZone: 'ဒေသခံအချိန်နှင့် ချိန်ကိုက်ပါ',
        themeMode: 'အပြင်အဆင်မုဒ်',
        chooseAppearance: 'သင့်ရွေးချယ်ထားသော အပြင်အဆင်ရွေးပါ',
        light: 'အလင်း',
        dark: 'အမှောင်',
        system: 'စနစ်',
        systemModeInfo: 'စနစ်မုဒ်သည် သင့်ကိရိယာ ဆက်တင်များနှင့် ကိုက်ညီသည်',
        locationServices: 'တည်နေရာဝန်ဆောင်မှုများ',
        locationEnabled: 'ဖွင့်ပြီး - သင့်တည်နေရာကို ခြေရာခံသည်',
        locationDisabled: 'ပိတ်ထားပြီး - တည်နေရာဝင်ရောက်ခွင့် ပိတ်ပင်ထားသည်',
        helpSupport: 'အကူအညီနှင့် ပံ့ပိုးမှု',
        // Directory
        addContact: 'ဆက်သွယ်မှုထည့်ပါ',
        searchContacts: 'အမည်၊ အခန်းကဏ္ဍ၊ မြို့ရှာပါ...',
        all: 'အားလုံး',
        admin: 'အက်ဒ်မင်',
        emergency: 'အရေးပေါ်',
        share: 'မျှဝေပါ',
        download: 'vCard ဒေါင်းလုဒ်လုပ်ပါ',
        print: 'ပရင့်ထုတ်ပါ',
        generateQR: 'QR ကုဒ်ဖန်တီးပါ',
        delete: 'ဖျက်ပါ',
        noContactsFound: 'ဆက်သွယ်မှုမတွေ့ပါ',
        tryAdjusting: 'သင့်ရှာဖွေမှု သို့မဟုတ် စစ်ထုတ်မှုများကို ပြင်ဆင်ကြည့်ပါ',
        contactInfo: 'ဆက်သွယ်မှုအချက်အလက်',
        callSign: 'ခေါ်ဆိုမှုအမှတ်အသား',
        addNewContact: 'ဆက်သွယ်မှုအသစ်ထည့်ပါ',
        required: 'လိုအပ်ပါသည်',
        enterFullName: 'အမည်အပြည့်အစုံ ထည့်ပါ',
        enterRole: 'ဥပမာ ပထမဆုံးတုံ့ပြန်သူ၊ ညှိနှိုင်းသူ',
        enterCallSign: 'ဥပမာ Alpha-1, Bravo-2',
        enterEmail: 'email@example.com',
        enterPhone: '+95-555-0123',
        userType: 'အမျိုးအစား',
        user: 'အသုံးပြုသူ',
        responder: 'တုံ့ပြန်သူ',
        fillRequired: 'လိုအပ်သောအချက်များ ပြည့်စုံစွာထည့်ပါ (အမည်၊ အီးမေးလ်၊ ဖုန်း)',
        // Chat
        newMessage: 'မက်ဆေ့ချ်အသစ်',
        typeMessage: 'မက်ဆေ့ချ်ရိုက်ပါ...',
        send: 'ပို့ပါ',
        encryptedConversation: 'အဆုံးမှအဆုံး ကုဒ်ဝှက်ထားသော စကားပြောခြင်း',
        attachments: 'ပူးတွဲဖိုင်များ',
        image: 'ပုံ',
        document: 'စာရွက်စာတမ်း',
        voiceMessage: 'အသံမက်ဆေ့ချ်',
        videoCall: 'ဗီဒီယိုခေါ်ဆိုမှု',
        liveLocation: 'လက်ရှိပြ တည်နေရာ',
        // System Status
        systemStatus: 'စနစ်အခြေအနေ',
        operationalStatus: 'လုပ်ဆောင်ခြင်းအခြေအနေ',
        alerts: 'လက်ရှိသတိပေးချက်များ',
        gpsSignal: 'GPS သတင်းအချက်အလက်',
        userStatus: 'အသုံးပြုသူအခြေအနေ',
        lastUpdated: 'နောက်ဆုံးပြင်ဆင်ချိန်',
        safe: 'ဘေးကင်းသည်',
        searching: 'ရှာဖွေနေသည်',
        close: 'ပိတ်ပါ',
        // Notifications
        totalNotifications: 'စုစုပေါင်း',
        unread: 'မဖတ်ရသေး',
        read: 'ဖတ်ပြီး',
        markAllRead: 'အားလုံးဖတ်ပြီးအမှတ်ပြပါ',
        // Common
        loading: 'တင်နေသည်...',
        error: 'အမှား',
        success: 'အောင်မြင်မှု',
        confirm: 'အတည်ပြုပါ',
        back: 'နောက်ပြန်သွားပါ',
        nextButton: 'နောက်တစ်ဆင့်',
        finish: 'ပြီးဆုံးပါ',
        yes: 'ဟုတ်ကဲ့',
        no: 'မဟုတ်ပါ',
        ok: 'ကောင်းပါပြီ',
        // Emergency / SOS
        imSafe: 'ကျွန်ုပ်ဘေးကင်းပါသည်',
        safeStatusUpdated: 'သင့်အခြေအနေကို ပြင်ဆင်ပြီး တုံ့ပြန်သူများနှင့် မျှဝေပြီးပါပြီ။',
        returnToDashboard: 'ပင်မစာမျက်နှာသို့ ပြန်သွားပါ',
        sosActivated: 'အရေးပေါ်ဖွင့်ပြီး',
        emergencyNotified: 'အရေးပေါ်ဝန်ဆောင်မှုများအား သင့်တည်နေရာကို အကြောင်းကြားပြီးပါပြီ။',
        broadcastingSignal: 'သတင်းအချက်အလက် ထုတ်လွှင့်နေသည်...',
        gettingLocation: 'သင့်လက်ရှိပြ တည်နေရာ ရယူနေသည်...',
        locationUnavailable: 'တည်နေရာ မရနိုင်ပါ (GPS ဖွင့်ပါ)',
        cancelAlert: 'သတိပေးချက် ပယ်ဖျက်ပါ',
        emergencyResponse: 'အရေးပေါ်တုံ့ပြန်မှု',
        shareStatusReport: 'သင့်အခြေအနေ သို့မဟုတ် ဖြစ်ရပ်မှတ်တမ်းတင်ပါ။',
        respondersNotified: 'တုံ့ပြန်သူများအား အကြောင်းကြားပါမည်။',
        sosHelp: 'အရေးပေါ် / အကူအညီ',
        reportAnIncident: 'ဖြစ်ရပ်မှတ်တမ်းတင်ပါ',
        floodPlacementHint: 'ရန်ကုန်မြစ်ကမ်းနံဘေးတွင် မြစ်ကမ်းဘေးနေအိမ်များ၊ ဆိပ်ကမ်းဒေသများနှင့် ကျွန်းကျေးရွပ်ရပ်များရှိသည်။ ရေကြီးဖြစ်ရပ်များကို လူထုအန္တရာယ်ရှိသော မြစ်ကမ်းဘေးတည်နေရာများတွင် ထည့်ပါ။ အတိအကျနေရာသတ်မှတ်ရန် အောက်ပါမြေပုံကို သုံးပါ။',
        reviewReport: 'အစီရင်ခံစာ ပြန်လည်သုံးသပ်ပါ',
        feed: 'ဖိဒ်',
        history: 'မှတ်တမ်း',
        mySubmissions: 'ကျွန်ုပ်တင်သွင်းထားသော အစီရင်ခံစာများ',
        noReportsSubmitted: 'အစီရင်ခံစာမရှိသေးပါ။',
        completePreparednessKit: 'ပြင်ဆင်မှုအရန်ပစ္စည်း ပြီးမြောက်ပါ',
        updateMedicalProfile: 'ဆေးဘက်ဆိုင်ရာပရိုဖိုင် ပြင်ဆင်ပါ',
        joinDrillSession: 'လေ့ကျင့်ခန်းအစည်းအဝေးတွင် ပါဝင်ပါ',
        fullyPreparedMessage: 'သင့်အား အပြည့်အဝပြင်ဆင်ပြီးပါပြီ။ ဘေးကင်းလုံခြုံမှု ထိန်းသိမ်းထားသည့်အတွက် ကျေးဇူးတင်ပါသည်။',
        closeBreakdown: 'ခွဲခြမ်းခြင်း ပိတ်ပါ',
        highZone: 'မြင့် ၇၆–၁၀၀',
        midZone: 'အလယ် ၄၁–၇၅',
        lowZone: 'နိမ့် ၀–၄၀',
        preparedness: 'ပြင်ဆင်မှု',
        deleteChecklistConfirm: 'ဤစာရင်းပါအချက်ကို ဖျက်မလား။',
        deleteDrillConfirm: 'ဤလေ့ကျင့်ခန်းအစည်းအဝေးကို ဖျက်မလား။',
        checklist: 'စာရင်း',
        drills: 'လေ့ကျင့်ခန်းများ',
        profileSettings: 'ပရိုဖိုင် ဆက်တင်',
        appPreferences: 'အက်ပ်ရွေးချယ်မှု',
        notificationSettings: 'အကြောင်းကြားချက် ဆက်တင်',
        emergencyPlan: 'အရေးပေါ်အစီအစဉ်',
        shareApp: 'အက်ပ်မျှဝေပါ',
        signOutConfirm: 'ထွက်မည်ဟု သေချာပါသလား။',
        highSeverity: 'ပြင်းထန်မှုမြင့်',
        moderateSeverity: 'ပြင်းထန်မှု အလယ်အလတ်',
        lowSeverity: 'ပြင်းထန်မှုနိမ့်',
        criticalSeverity: 'ပြင်းထန်မှု အလွန်မြင့်',
        drillsAndLogs: 'လေ့ကျင့်ခန်းများနှင့် မှတ်တမ်းများ',
        checklistProgress: 'စာရင်းတိုးတက်မှု',
        adminMode: 'အက်ဒ်မင်မုဒ်',
        upcomingDrills: 'လာမည့်လေ့ကျင့်ခန်းများ',
        pastLogs: 'အတိတ်မှတ်တမ်းများ',
        editItem: 'အချက်ပြင်ဆင်ပါ',
        newChecklistItem: 'စာရင်းအချက်အသစ်',
        editDrill: 'လေ့ကျင့်ခန်းပြင်ဆင်ပါ',
        newDrillSession: 'လေ့ကျင့်ခန်းအစည်းအဝေးအသစ်',
        newTutorialItem: 'သင်ခန်းစာအသစ်',
        editTutorial: 'သင်ခန်းစာပြင်ဆင်ပါ',
        newLearnItem: 'လေ့လာချက်အချက်အသစ်',
        editLearnItem: 'လေ့လာချက်အချက်ပြင်ဆင်ပါ',
        learnItemType: 'အမျိုးအစား',
        learnItems: 'လေ့လာချက်အချက်များ',
        noLearnItems: 'လေ့လာချက်အချက်မရှိသေးပါ။',
        deleteLearnItemConfirm: 'ဤလေ့လာချက်အချက်ကို ဖျက်မလား။',
        deleteTutorialConfirm: 'ဤသင်ခန်းစာကို ဖျက်မလား။',
        noChecklistItems: 'စာရင်းအချက်မရှိပါ။',
        noUpcomingDrills: 'လာမည့်လေ့ကျင့်ခန်းမရှိသေးပါ။',
        noPastLogs: 'အတိတ်မှတ်တမ်းမရှိသေးပါ။',
        noNotesRecorded: 'မှတ်ချက်မရှိပါ။',
        participants: 'ပါဝင်သူများ',
        register: 'မှတ်ပုံတင်ပါ',
        title: 'ခေါင်းစဉ်',
        xpPointsLabel: 'XP မှတ်များ',
        privacyPolicy: 'ကိုယ်ရေးအချက်အလက် မူဝါဒ',
        privacyControls: 'ကိုယ်ရေးအချက်အလက် ထိန်းချုပ်မှုများ',
        complete: 'ပြီးမြောက်ပါ',
        adminPanel: 'အက်ဒ်မင် ပြင်ညီ',
        date: 'ရက်စွဲ',
        dateLabel: 'ရက်စွဲ',
        notSet: 'မသတ်မှတ်ရသေး',
        pushNotifications: 'ပျံ့နှံ့အကြောင်းကြားချက်များ',
        emailNotifications: 'အီးမေးလ် အကြောင်းကြားချက်များ',
        profileVisibility: 'ပရိုဖိုင်မြင်ကွင်း',
        shareLocation: 'တည်နေရာမျှဝေပါ',
        deleteAccount: 'အကောင့်ဖျက်ပါ',
        systemOperational: 'စနစ်လည်ပတ်နေသည်',
        allSystemsNormal: 'စနစ်အားလုံး ပုံမှန်လည်ပတ်နေသည်။',
        criticalNotifications: 'အလွန်အရေးကြီးသော အကြောင်းကြားချက်များ',
        yourStatus: 'သင့်အခြေအနေ',
        currentSafetyStatus: 'လက်ရှိဘေးကင်းလုံခြုံမှုအခြေအနေ',
        network: 'ကွန်ယက်',
        emergencyResponseTeam: 'အရေးပေါ်တုံ့ပြန်မှုအဖွဲ့',
        communitySafetyGroup: 'လူထုဘေးကင်းလုံခြုံမှုအဖွဲ့',
        adminSupport: 'အက်ဒ်မင် ပံ့ပိုးမှု',
        localResponders: 'ဒေသခံတုံ့ပြန်သူများ',
        aiSafetyAssistant: 'AI ဘေးကင်းလုံခြုံမှု လက်ထောက်',
        aiTyping: 'AI ရိုက်နေသည်...',
        aiUnavailableFallback: 'လူ့တုံ့ပြန်သူများ အင်တာနက်မရှိပါ။ ဘေးကင်းလုံခြုံမှုအကြံပြုချက်အတွက် AI လက်ထောက်သည် ၂၄/၇ ရနိုင်ပါသည်။',
        urgentHelp: 'အလွန်အရေးကြီး အကူအညီ',
        sosSigns: 'အရေးပေါ်အမှတ်အသားများ',
        emojiUrgentHelp: 'အလွန်အရေးကြီး အကူအညီ',
        emojiEmergency: 'အရေးပေါ်',
        emojiWarning: 'သတိပေးချက်',
        emojiMedical: 'ဆေးဘက်',
        emojiFire: 'မီး',
        emojiFlood: 'ရေကြီးခြင်း',
        emojiEarthquake: 'ငလျင်',
        emojiOk: 'ကောင်းပါပြီ',
        emojiShelter: 'ခိုလှုံရာ',
        emojiNoElectricity: 'လျှပ်စစ်မရှိ',
        emojiNoInternet: 'အင်တာနက်မရှိ',
        emojiWounded: 'ဒဏ်ရာရသည်',
        emojiCannotSpeak: 'စကားမပြောနိုင်',
        emojiTrapped: 'ပိတ်မိနေသည်',
        emojiNeedWater: 'ရေလိုသည်',
        emojiNeedFood: 'အစားအစာလိုသည်',
        emojiSilent: 'ဆိတ်ဆိတ်နေပါ',
        emojiChemical: 'ဓာတုပစ္စည်းအန္တရာယ်',
        emojiPoison: 'အဆိပ်',
        emojiShooterActive: 'သေနတ်သမား',
        activityStatistics: 'လုပ်ဆောင်ချက် စာရင်းအင်း',
        skillsAndCertifications: 'ကျွမ်းကျင်မှုနှင့် အသိအမှတ်ပြုလက်မှတ်များ',
        suggestedSkills: 'အကြံပြုကျွမ်းကျင်မှုများ',
        experiencePoints: 'အတွေ့အကြုံမှတ်များ',
        volunteerPoints: 'စေတနာ့ဝန်ထမ်းမှတ်များ',
        levelProgress: 'အဆင့်တိုးတက်မှု',
        nextLevel: 'နောက်အဆင့်',
        fullName: 'အမည်အပြည့်အစုံ',
        add: 'ထည့်ပါ',
        noSkillsAdded: 'ကျွမ်းကျင်မှုမထည့်ရသေးပါ။',
        addFirstSkill: 'သင့်ပထမကျွမ်းကျင်မှုထည့်ပါ',
        firstAid: 'ပထမဆုံးအကူအညီ',
        cprCertified: 'CPR အသိအမှတ်ပြု',
        fireSafety: 'မီးဘေးကင်းလုံခြုံမှု',
        emergencyResponseSkill: 'အရေးပေါ်တုံ့ပြန်မှု',
        searchAndRescue: 'ရှာဖွေကယ်ဆယ်ခြင်း',
        emergencyKitAchievement: 'အရေးပေါ်အရန်ပစ္စည်း',
        firstAidTrained: 'ပထမဆုံးအကူအညီ သင်ကြားပြီး',
        homeSafety: 'အိမ်ဘေးကင်းလုံခြုံမှု',
        certified: 'အသိအမှတ်ပြု',
        checklistBuildKit: 'အခြေခံအရေးပေါ်အရန်ပစ္စည်း ပြုလုပ်ပါ',
        checklistSaveNumbers: 'ဒေသခံအရေးပေါ်နံပါတ်များ သိမ်းပါ',
        checklistStoreWater: 'ရေ ၃ ရက်သိမ်းပါ (၁ ဂါလံ/ဦး/နေ့)',
        checklistStockFood: 'မပျက်စီးတတ်သော အစားအစာ ၃ ရက် သိုလှောင်ပါ',
        checklistCanOpener: 'လက်ဖြင့်အဖွင့်ကိရိယာ',
        checklistRadio: 'ဘက်ထရီ သို့မဟုတ် လက်လှည့်ရေဒီယို',
        checklistFlashlight: 'မီးအိမ် + အပိုဘက်ထရီများ',
        checklistWhistle: 'အကူအညီအတွက် လေမှုတ်သံ',
        checklistWrench: 'အသုံးအဆောင်များ ပိတ်ရန် ထိုးနပ်ရာ/ပြေး',
        checklistLocalMaps: 'ဒေသခံမြေပုံများ (စာရွက်)',
        checklistMedications: 'ဆေးညွှန်းဆေးများ (၇ ရက်ပမာဏ)',
        checklistDustMask: 'ညစ်ညမ်းလေအတွက် မျက်နှာဖုံး (N95)',
        checklistTowelettes: 'အစိုဓာတ်တဘက်များ/အမှိုက်အိတ်များ',
        checklistInsurance: 'အာမခံမူဝါဒမိတ္တူများ',
        checklistIdRecords: 'မှတ်ပုံတင်နံပါတ်နှင့် ဘဏ်အကောင့်မှတ်တမ်းများ',
        checklistCash: 'အရေးပေါ်အတွက် ငွေသား',
        checklistSecureFurniture: 'အလေးချိန်ရှိပရိဘောဂများ (စာအုပ်စင်များ၊ ဗီရိုများ) နံရံများတွင်ပ်သပ်ရပ်ရပ်ထားပါ',
        checklistDropCoverHold: 'အိမ်ထောင်စုနှင့် ငိုက်ပါ-ကွယ်ပါ-ကိုင်ထားပါ လေ့ကျင့်ပါ',
        checklistGasShutoff: 'ဓာတ်ငွေ့ပိတ်ဆို့မှုတံခါး တည်နေရာသိပါ',
        checklistSturdyShoes: 'ခြေနင်းဖိနပ်ကို အိပ်ရာအနီးတွင် ထားပါ (ဖန်/အမှိုက်များအတွက်)',
        checklistTsunamiRoute: 'မြင့်မားသောမြေပြင်သို့ ထွက်ပြေးရေးလမ်းကြောင်း သိပါ',
        checklistTsunamiZone: 'ဆူနာမီအန္တရာယ်ဇုန်နှင့် ဘေးကင်းတွေ့ဆုံရာကို သိပါ',
        checklistGoBag: 'မြန်မြန်ထွက်ပြေးရန် သွားအိတ် အဆင်သင့်ထားပါ',
        checklistSecureOutdoor: 'မိုးသက်လေပြင်းမကျမီ အပြင်ပစ္စည်းများပ်သပ်ရပ်ရပ်ထားပါ',
        checklistStormShelter: 'အနီးဆုံးမိုးသက်လေပြင်း ခိုလှုံရာ တည်နေရာသိပါ',
        checklistChargeDevices: 'မိုးသက်လေပြင်းမကျမီ ကိရိယာအားလုံး အားသွင်းပါ',
        checklistSmokeDetectors: 'မီးခိုးဖမ်းယန္တရားများ တပ်ဆင်ပြီး စမ်းသပ်ပါ',
        checklistFireExtinguisher: 'မီးငြှိမ်းသတ်စက် မီးဖိုထဲနှင့် ထွက်ပေါက်အနီးတွင် ထားပါ',
        checklistEscapePlan: 'အခန်းတစ်ခန်းလျှင် ထွက်ပေါက် ၂ ခုပါ အိမ်ထွက်ပြေးရေးအစီအစဉ်',
        checklistMeetingPoint: 'အိမ်ထောင်စုအတွက် ပြင်ပတွေ့ဆုံရာကို သတ်မှတ်ပါ',
        drillAnnualFire: 'နှစ်စဉ်မီးလေ့ကျင့်ခန်း',
        drillEarthquake: 'ငလျင်စမ်းသပ်ခြင်း',
        drillActiveShooter: 'သေနတ်သမားလေ့ကျင့်ခန်း',
        evacuation: 'ထွက်ပြေးခြင်း',
        lockdown: 'ပိတ်ဆို့ခြင်း',
        learn: 'လေ့လာပါ',
        learnSubtitle: 'ညွှန်ကြားချက်များ၊ သင်ခန်းစာများနှင့် အရင်းအမြစ်များ',
        howToGuides: 'SafeSphere အသုံးပြုပုံ',
        readMore: 'ပိုမိုဖတ်ပါ',
        tutorialVideos: 'သင်ခန်းစာဗီဒီယိုများနှင့် ညွှန်ကြားချက်များ',
        externalResources: 'ပြင်ပအရင်းအမြစ်များ',
        learnMore: 'သင်ခန်းစာများနှင့် အရင်းအမြစ်များ ကြည့်ပါ',
        learnReportIncident: 'ဖြစ်ရပ်မှတ်တမ်းတင်ပါ',
        learnReportIncidentDesc: 'အရေးပေါ် သို့မဟုတ် ဖြစ်ရပ်မှတ်တမ်းတင်ပါကို နှိပ်ပြီး သင့်တည်နေရာနှင့် အခြေအနေကို တုံ့ပြန်သူများနှင့် မျှဝေပါ။ ပိုမြန်အကူအညီအတွက် ဓာတ်ပုံများနှင့် အချက်အလက်များ ထည့်ပါ။',
        learnChecklist: 'သင့်စာရင်းပြီးမြောက်ပါ',
        learnChecklistDesc: 'သင့်အရေးပေါ်အရန်ပစ္စည်းကို တစ်ဆင့်ချင်း ပြုလုပ်ပါ။ ပြီးမြောက်အမှတြပြီး ဘေးကင်းလုံခြုံမှုရမှတ်နှင့် အောင်မြင်မှုများ ရယူပါ။',
        learnLiveMap: 'လက်ရှိပြ မြေပုံသုံးပါ',
        learnLiveMapDesc: 'မြေပုံတွင် ဖြစ်ရပ်များ၊ အရင်းအမြစ်များနှင့် တုံ့ပြန်သူများ ကြည့်ပါ။ အချက်အလက်များအတွက် မှတ်အမှတ်များကို နှိပ်ပါ။ လက်ရှိပြ လမ်းကြောင်းအတွက် တည်နေရာဖွင့်ပါ။',
        learnChat: 'တုံ့ပြန်သူများနှင့် ချက်ပါ',
        learnChatDesc: 'ကုဒ်ဝှက်မက်ဆေ့ချ်များ ပို့ပါ၊ သင့်လက်ရှိပြ တည်နေရာ မျှဝေပါ သို့မဟုတ် ဗီဒီယိုခေါ်ဆိုမှု စတင်ပါ။ အမြန်အခြေအနေအပ်ဒိတ်အတွက် အရေးပေါ်အမှတ်အသားများ သုံးပါ။',
        tutorialEmergencyBasics: 'အရေးပေါ်ပြင်ဆင်မှု အခြေခံများ',
        tutorialEmergencyBasicsDesc: 'အရေးပေါ်အခြေအနေများအတွက် သင့်အိမ်နှင့် မိသားစုကို ပြင်ဆင်ပုံ။',
        tutorialDisasterPrep: 'ဘေးဒ္ခပြင်ဆင်မှု',
        tutorialDisasterPrepDesc: 'အရန်ပစ္စည်းပြုလုပ်ပါ၊ အစီအစဉ်ချပါ၊ သတင်းအချက်အလက် ရယူပါ။',
        tutorialEarthquake: 'ငလျင်ဘေးကင်းလုံခြုံမှု ဗီဒီယိုစီးရီး',
        tutorialEarthquakeDesc: 'ငလျင်အတွက် ပြင်ဆင်ပုံနှင့် ငလျင်အတွင်းဘေးကင်းစွာနေပုံ။',
        tutorialFirstAid: 'ပထမဆုံးအကူအညီ အခြေခံများ',
        tutorialFirstAidDesc: 'အရေးပေါ်အခြေအနေများအတွက် အခြေခံပထမဆုံးအကူအညီ ကျွမ်းကျင်မှုများ လေ့လာပါ။',
        tutorialTrauma: 'စိတ်ဒဏ်ရာအတွက် ဆရာဝန်',
        tutorialTraumaDesc: 'စိတ်လှုပ်ရှားမှုကြီးစွာဖြစ်ချိန် တစ်စုံတစ်ယောက်ကို အကူအညီပေးခြင်း။',
        tutorialCpr: 'CPR နှင့် AED',
        tutorialCprDesc: 'CPR ပြုလုပ်ပုံနှင့် AED သုံးပုံ။',
        tutorialEvac: 'အရေးပေါ်ထွက်ပြေးခြင်း',
        tutorialEvacDesc: 'ပြင်ဆင်မှု ၃ ဆင့်ဖြင့် Red Cross အဆင်သင့်ဖြစ်ပါ။',
        resourceRedCross: 'အရေးပေါ်ပြင်ဆင်မှုနှင့် ပထမဆုံးအကူအညီ',
        resourceFEMA: 'ဖက်ဒရယ်အရေးပေါ်စီမံခန့်ခွဲမှု',
        resourceWHO: 'ကမ္ဘာ့ကျန်းမာရေးအရေးပေါ်များ',
        resourceCDC: 'ပြည်သူ့ကျန်းမာရေးအရေးပေါ်များ',
        achFirstDrill: 'ပထမလေ့ကျင့်ခန်း',
        achProfile: 'ပရိုဖိုင်',
        achKit: 'အရန်ပစ္စည်းအဆင်သင့်',
        achExpert: 'ကျွမ်းကျင်သူ',
        onboardingWelcome: 'SafeSphere မှ ကြိုဆိုပါသည်',
        onboardingWelcomeDesc: 'အရေးပေါ်အခြေအနေများအတွက် အဆင်သင့်ဖြစ်ပါ။ အရန်ပစ္စည်းပြုလုပ်ပါ၊ လေ့ကျင့်ခန်းများ ပြီးမြောက်ပါ၊ တိုးတက်သည်နှင့်အမျှ XP ရယူပါ။',
        onboardingPrepare: 'ပြင်ဆင်ပါ',
        onboardingPrepareDesc: 'အရေးပေါ်အရန်ပစ္စည်းပြုလုပ်ရန် စာရင်းသုံးပါ၊ လေ့ကျင့်ရန် လေ့ကျင့်ခန်းများတွင် ပါဝင်ပါ၊ တိုးတက်သည်နှင့်အမျှ XP ရယူပါ။',
        onboardingLearn: 'လေ့လာပါ',
        onboardingLearnDesc: 'သင်ခန်းစာများ ကြည့်ပြီး အရင်းအမြစ်များ ရယူပါ။ ညွှန်ကြားချက်များ၊ ဗီဒီယိုများနှင့် ကျွမ်းကျင်သူအကြံပြုချက်များအတွက် လေ့လာချက်ကဏ္ဍသို့ သွားပါ။',
        onboardingReady: 'သင် အဆင်သင့်ဖြစ်ပါပြီ။',
        onboardingReadyDesc: 'အောက်ပါစာရင်းမှ စတင်ပါ၊ လေ့ကျင့်ခန်းများ ပြီးမြောက်ပါ၊ သင်ခန်းစာများ ကြည့်ပါ။ ဘေးကင်းစွာနေပါ။',
        onboardingGetStarted: 'စလိုက်ပါမည်',
        onboardingViewLearn: 'လေ့လာချက်နှင့် သင်ခန်းစာများ ကြည့်ပါ',
        onboardingSkip: 'ကျော်ပါ',
        tutorials: 'သင်ခန်းစာများ',
        learnAndEarn: 'ဗီဒီယိုများမှ လေ့လာပြီး XP ရယူပါ။',
        watchTutorial: 'ကြည့်ပါ',
        markComplete: 'ပြီးမြောက်အမှတ်ပြပါ',
        completed: 'ပြီးမြောက်ပါပြီ',
        earnXp: 'XP {xp} ရယူပါ',
        noTutorials: 'သင်ခန်းစာမရှိပါ။',
        yourPrivacyMatters: 'သင့်ကိုယ်ရေးအချက်အလက် အရေးကြီးသည်',
        euDataProtection: 'EU ကိုယ်ရေးအချက်အလက် ကာကွယ်မှုနှင့် ကိုက်ညီသည်',
        privacyIntro: 'SafeSphere သည် EU GDPR စည်းမျဉ်းများနှင့် နိုင်ငံတကာ ကိုယ်ရေးအချက်အလက် စံနှုန်းများနှင့်အညီ သင့်ကိုယ်ရေးအချက်အလက်ကို ကာကွယ်ရန် ကတိပြုပါသည်။',
        dataCollection: '၁။ ဒေတာစုဆောင်းခြင်း',
        dataCollectionDesc: 'အရေးပေါ်လမ်းကြောင်းနှင့် ဘေးကင်းလုံခြုံမှုသတိပေးချက်များ ပေးရန် တည်နေရာဒေတာကို စုဆောင်းသည်။ ဤဒေတာကို ကုဒ်ဝှက်ထားပြီး အရေးပေါ်ဖွင့်ပါ သို့မဟုတ် အစီရင်ခံစာတင်သည့်အခါသာ အရေးပေါ်တုံ့ပြန်သူများနှင့် မျှဝေသည်။',
        locationNeverSold: 'သင့်တည်နေရာကို တတိယပါတီများသို့ မရောင်းချပါ သို့မဟုတ် ကြော်ငြာရည်ရွယ်ချက်ဖြင့် မသုံးပါ။',
        endToEndEncryption: '၂။ အဆုံးမှအဆုံး ကုဒ်ဝှက်ခြင်း',
        endToEndEncryptionDesc: 'အဖွဲ့မက်ဆေ့ချ်အားလုံး အဆုံးမှအဆုံး ကုဒ်ဝှက်ထားသည်။ ကျွန်ုပ်တို့ သင့်မက်ဆေ့ချ်များကို မဖတ်နိုင်ပါ သို့မဟုတ် သင့်ခေါ်ဆိုမှုများကို မနားထောင်နိုင်ပါ။ ကုဒ်ဝှက်သော့များကို သင့်ကိရိယာတွင် ဒေသခံသိမ်းဆည်းထားသည်။',
        aesEncryption: 'AES ကုဒ်ဝှက်ခြင်း',
        zeroAccessPolicy: 'သုညဝင်ရောက်ခွင့် မူဝါဒ',
        userRights: '၃။ အသုံးပြုသူအခွင့်အရေးများ',
        userRightsDesc: 'ဆက်တင်မီနူး သို့မဟုတ် ပံ့ပိုးမှုနှင့် ဆက်သွယ်၍ သင့်ကိုယ်ရေးအချက်အလက်ကို ကြည့်ရှု၊ ပြင်ဆင် သို့မဟုတ် ဖျက်ပစ်ခွင့် ရှိသည်။',
        rightToAccess: 'သင့်ဒေတာကို ကြည့်ရှုခွင့်',
        rightToRectification: 'ပြင်ဆင်ခွင့်',
        rightToErasure: 'ဖျက်ပစ်ခွင့် (မေ့လျော့ခွင့်)',
        rightToPortability: 'ဒေတာသယ်ယူခွင့်',
        emergencyDisclosure: '၄။ အရေးပေါ်ဖော်ထုတ်ခြင်း',
        emergencyDisclosureDesc: 'အသက်အန္တရာယ်ရှိသော အခြေအနေများတွင် ကယ်ဆယ်ရေးလုပ်ငန်းများကို ကူညီရန် အတည်ပြုထားသော အရေးပေါ်ဝန်ဆောင်မှုများနှင့် သင့်နောက်ဆုံးသိထားသော တည်နေရာကို မျှဝေနိုင်သည်။',
        whenWeShareData: 'ကျွန်ုပ်တို့ သင့်ဒေတာကို မျှဝေသည့်အခါ။',
        triggerSos: 'သင် အရေးပေါ်သတိပေးချက် ဖွင့်သည်',
        emergencyRequest: 'အရေးပေါ်ဝန်ဆောင်မှုများ တည်နေရာအကူအညီ တောင်းသည်',
        legalObligation: 'အန္တရာယ်ကာကွယ်ရန် ဥပဒေအရ တာဝန်',
        questionsOrConcerns: 'မေးခွန်းများ သို့မဟုတ် စိုးရိမ်မှုများ။',
        privacyContact: 'ဤကိုယ်ရေးအချက်အလက် မူဝါဒ သို့မဟုတ် ကျွန်ုပ်တို့ ဒေတာကို ကိုင်တွယ်ပုံအကြောင်း မေးခွန်းများရှိပါက ကျွန်ုပ်တို့၏ ဒေတာကာကွယ်မှု အရာရှိထံ ဆက်သွယ်ပါ။',
        allRightsReserved: 'အခွင့်အရေးအားလုံး ချုပ်ကိုင်ထားသည်။',
        euGdprCompliant: 'EU GDPR နှင့် ကိုက်ညီသည်',
        isoCertified: 'ISO 27001 အသိအမှတ်ပြု',
        helpAndSupport: 'အကူအညီနှင့် ပံ့ပိုးမှု',
        helpSupportTitle: 'SafeSphere အကူအညီနှင့် ပံ့ပိုးမှု',
        emailSupport: 'အီးမေးလ် ပံ့ပိုးမှု',
        responseTime: 'တုံ့ပြန်ချိန် ၂-၄ နာရီ',
        emergencyHotline: 'အရေးပေါ်ဖုန်းလိုင်း',
        liveChat: 'ချက်',
        liveChatDesc: 'အက်ပ်တွင် ၂၄/၇ ရနိုင်ပါသည်',
        helpCenter: 'အကူအညီဗဟို',
        technicalSupport: 'နည်းပညာပံ့ပိုးမှု',
        emergencyCallNote: 'အသက်အန္တရာယ်ရှိသော အရေးပေါ်အခြေအနေများအတွက် သင့်ဒေသခံ အရေးပေါ်ဝန်ဆောင်မှုများကို ချက်ချင်း ခေါ်ပါ (၁၁၂၊ ၁၂၂၊ ၁၃၃၊ ၁၄၄၊ ၉၁၁ စသည်)။',
        alertPreferences: 'သတိပေးချက် ရွေးချယ်မှုများ',
        deliveryMethods: 'ပို့ဆောင်နည်းများ',
        emergencyAlertsLabel: 'အရေးပေါ်သတိပေးချက်များ',
        reportUpdates: 'အစီရင်ခံစာ အပ်ဒိတ်များ',
        systemMessages: 'စနစ်မက်ဆေ့ချ်များ',
        statusChanges: 'အခြေအနေပြောင်းလဲမှုများ',
        appUpdates: 'အက်ပ်အပ်ဒိတ်များ',
        instantMobileAlerts: 'ချက်ချင်းမိုဘိုင်းသတိပေးချက်များ',
        offlineModeFeatures: 'အင်တာနက်မရှိ မုဒ် လုပ်ဆောင်ချက်များ',
        offlineFeaturesDesc: 'အင်တာနက်မရှိသည့်တိုင် အချက်ပြနိုင်စေရန် အင်တာနက်မလိုသော လုပ်ဆောင်ချက်များ ဖွင့်ပါ။',
        whyOfflineFeaturesMatter: 'အင်တာနက်မရှိ လုပ်ဆောင်ချက်များ အရေးကြီးရချက်',
        offlineFeaturesBullets: 'အရေးပေါ်အခြေအနေများတွင် အင်တာနက်မရနိုင်ပါ။ ဤလုပ်ဆောင်ချက်များဖြင့် သင်တို့သည်။',
        bluetoothBeacon: 'ဘလူးတုသ် ဘီကန်',
        broadcastSosBluetooth: 'ဘလူးတုသ်ဖြင့် အရေးပေါ်ထုတ်လွှင့်ပါ',
        gpsLocation: 'GPS တည်နေရာ',
        trackLocationOffline: 'အင်တာနက်မရှိသည့်တိုင် တည်နေရာခြေရာခံပါ',
        offlineMode: 'အင်တာနက်မရှိ မုဒ်',
        workWithoutInternet: 'အင်တာနက်မလို လုပ်ဆောင်ပါ',
        localStorageSync: 'ဒေသခံသိမ်းဆည်းမှု ချိန်ကိုက်ပါ',
        cacheDataLocally: 'ဒေတာကို ဒေသခံသိမ်းပါ',
        emergencyBeacon: 'အရေးပေါ်ဘီကန်',
        sendSosWithoutInternet: 'အင်တာနက်မရှိသည့်တိုင် အရေးပေါ်ပို့ပါ',
        dataManagement: 'ဒေတာစီမံခန့်ခွဲမှု',
        downloadMyData: 'ကျွန်ုပ်ဒေတာ ဒေါင်းလုဒ်လုပ်ပါ',
        clearCache: 'ကက်ရှ်ရှင်းပါ',
        clearCacheConfirm: 'ကက်ရှ်ဒေတာအားလုံး ရှင်းမလား။ သင့်ပရိုဖိုင်နှင့် ဆက်တင်များ ထားပါမည်။',
        deleteAccountConfirm: 'သင့်အကောင့်နှင့် ဒေတာအားလုံး ဖျက်မလား။ ပြန်မလုပ်နိုင်ပါ။ သင် ထွက်သွားပါမည်။',
        passwordAndAuthentication: 'စကားဝှက်နှင့် စစ်မှန်ခြင်း',
        changePassword: 'စကားဝှက်ပြောင်းပါ',
        currentPassword: 'လက်ရှိစကားဝှက်',
        newPassword: 'စကားဝှက်အသစ်',
        confirmNewPassword: 'စကားဝှက်အသစ် အတည်ပြုပါ',
        updatePassword: 'စကားဝှက်အပ်ဒိတ်လုပ်ပါ',
        passwordChangedSuccess: 'စကားဝှက် အောင်မြင်စွာ ပြောင်းပြီးပါပြီ။',
        twoFactorAuthentication: 'နှစ်ဆင့်စစ်မှန်ခြင်း',
        extraSecurityLayer: 'အပိုလုံခြုံရေးအလွှာ',
        twoFactorDesc: 'အကောင့်ဝင်သည့်အခါ အတည်ပြုကုဒ် လိုအပ်ခြင်းဖြင့် အပိုလုံခြုံရေးအလွှာ ထည့်ပါ။',
        enable2fa: '2FA ဖွင့်ပါ',
        enableFaceId: 'Face ID ဖွင့်ပါ',
        twoFactorFaceIdRequirement: 'စစ်မှန်ခြင်းအတွက် 2FA နှင့် Face ID နှစ်မျိုးလုံး ဖွင့်ပါ။',
        faceId: 'Face ID',
        faceIdRequirementError: 'Face ID စစ်မှန်ခြင်းအတွက် ဆက်တင် > လုံခြုံရေးတွင် 2FA နှင့် Face ID နှစ်မျိုးလုံး ဖွင့်ပါ။',
        activeSessions: 'လက်ရှိအစည်းအဝေးများ',
        currentSession: 'လက်ရှိအစည်းအဝေး',
        lastActive: 'နောက်ဆုံးအသက်ဝင်ချိန်',
        endAllOtherSessions: 'အခြားအစည်းအဝေးအားလုံး ပြီးဆုံးပါ',
        endAllOtherSessionsConfirm: 'အခြားအစည်းအဝေးအားလုံး ပြီးဆုံးမလား။ ဤကိရိယာတွင် အကောင့်ဝင်နေမည်။',
        otherDevices: 'အခြားကိရိယာများ',
        active: 'အသက်ဝင်သည်',
        disablingLocationWarning: 'တည်နေရာဝန်ဆောင်မှုများ ပိတ်ခြင်းသည် အရေးပေါ်တုံ့ပြန်မှုနှင့် ဘေးကင်းလုံခြုံမှုသတိပေးချက်များကို ကန့်သတ်နိုင်သည်။',
        locationDataEncrypted: 'တည်နေရာဒေတာကို ကုဒ်ဝှက်ထားပြီး အရေးပေါ်အခြေအနေများတွင်သာ မျှဝေသည်။ ကျွန်ုပ်တို့ သင့်ကိုယ်ရေးအချက်အလက်ကို လေးစားပါသည်။',
        syncReportsWhenOnline: 'အင်တာနက်ရှိသည့်အခါ အစီရင်ခံစာများ ချိန်ကိုက်ရန် စီစဉ်ပါ',
        offlineBullet1: 'အနီးဆုံးကိရိယာများသို့ ဘလူးတုသ်ဖြင့် အချက်ပြမှုများ ပို့ပါ',
        offlineBullet2: 'ချိတ်ဆက်ပြန်ရောက်သည့်အခါ သင့် GPS တည်နေရာ မျှဝေပါ',
        offlineBullet3: 'အင်တာနက်မရှိသည့်တိုင် သိမ်းဆည်းထားသော အရေးပေါ်အရင်းအမြစ်များ သုံးပါ',
        commandCenter: 'ညွှန်ကြားရေးဗဟို',
        incidents: 'ဖြစ်ရပ်များ',
        logistics: 'ထောက်ပံ့ရေး',
        triage: 'အမျိုးအစားခွဲခြင်း',
        team: 'အဖွဲ့',
        safetyMap: 'ဘေးကင်းလုံခြုံမှုမြေပုံ',
        qrScanner: 'QR စကင်နာ',
        scanSafesphereQrCodes: 'SafeSphere QR ကုဒ်များ စကင်ပါ',
        rescueCenterFound: 'ကယ်ဆယ်ရေးဗဟို တွေ့ရှိပါပြီ။',
        nearestEmergencyFacilityScanned: 'အနီးဆုံးအရေးပေါ်ဌာန စင်ပြီး',
        qrCodeId: 'QR ကုဒ် ID။',
        scanAgain: 'ပြန်စကင်ပါ',
        callNow: 'ယခုခေါ်ပါ',
        scanning: 'စကင်နေသည်...',
        positionQrInFrame: 'QR ကုဒ်ကို ဘောင်အတွင်း ထားပါ',
        phoneNumberCopied: 'ဖုန်းနံပါတ် ကလစ်ဘုတ်သို့ ကူးပြီးပါပြီ။',
        signInSuccess: 'သင် အကောင့်ဝင်ပြီးပါပြီ။',
        loggedOutSuccess: 'သင် ထွက်ပြီးပါပြီ။',
        signOutConfirmShort: 'ထွက်မည်ဟု သေချာပါသလား။',
        areYouSure: 'သေချာပါသလား။',
        savedSuccessfully: 'အောင်မြင်စွာ သိမ်းပြီးပါပြီ။',
        deletedSuccessfully: 'အောင်မြင်စွာ ဖျက်ပြီးပါပြီ။',
        deleteItemConfirm: 'ဤအချက်ကို ဖျက်မည်ဟု သေချာပါသလား။ ပြန်မလုပ်နိုင်ပါ။',
        permissionDenied: 'ခွင့်ပြုချက် ငြင်းပယ်ခံရသည်',
        permissionDeniedAdmin: 'ခွင့်ပြုချက် ငြင်းပယ်ခံရသည်။ အက်ဒ်မင်များသာ မှတ်တမ်းများ ဖျက်နိုင်သည်။',
        markResolvedArchive: 'ပြီးမြောက်အမှတြပြီး မော်ကွန်းသွင်းမလား။',
        scanQrCode: 'QR ကုဒ် စကင်ပါ',
        inventoryLog: 'စာရင်းမှတ်တမ်း',
        triageBoard: 'အမျိုးအစားခွဲခြင်း ဘုတ်',
        teamMembers: 'အဖွဲ့ဝင်များ',
        searchIncidents: 'ဖြစ်ရပ်များ ရှာပါ...',
        statusAll: 'အခြေအနေ။ အားလုံး',
        typeAll: 'အမျိုးအစား။ အားလုံး',
        newItem: 'အချက်အသစ်',
        noReportsFound: 'ဤမြင်ကွင်းတွင် အစီရင်ခံစာမတွေ့ပါ။',
        view: 'ကြည့်ပါ',
        addPoint: 'အမှတ်ထည့်ပါ',
        drawPath: 'လမ်းကြောင်းဆွဲပါ',
        evacRoute: 'ထွက်ပြေးရေးလမ်းကြောင်း',
        transportRoad: 'သယ်ယူပို့ဆောင်ရေး လမ်း',
        clear: 'ရှင်းပါ',
        tapMapToPlace: 'ထည့်ရန် မြေပုံနှိပ်ပါ',
        tapMapToDraw: 'ဆွဲရန် မြေပုံနှိပ်ပါ',
        pathLabel: 'လမ်းကြောင်း',
        newAssetDetails: 'ပစ္စည်းအချက်အလက်အသစ်',
        editAsset: 'ပစ္စည်းပြင်ဆင်ပါ',
        labelName: 'အမှတ်အသား / အမည်',
        mainExitPlaceholder: 'ဥပမာ ပင်မထွက်ပေါက်',
        optionalDetailsPlaceholder: 'ရွေးချယ်အချက်အလက်...',
        exit: 'ထွက်ပေါက်',
        meetingPoint: 'တွေ့ဆုံရာ',
        extinguisher: 'မီးငြှိမ်းသတ်စက်',
        hydrant: 'ရေဘုံး',
        heavyRainExpected: 'မိုးသည်းထန်စွာ ရွာမည်ဟု မျှော်မှန်းသည်။ နိမ့်သောဒေသများ ရှောင်ပါ။',
        stayHydrated: 'ရေသောက်ပါ နှင့် နေပူကို ရှောင်ပါ။',
        floodType: 'ရေကြီးခြင်း',
        fireType: 'မီးလောင်ခြင်း',
        streetFloodedNearPark: 'ပန်းခြံအနီး လမ်းရေလျံ',
        smallBrushFireSpotted: 'ချုံပုတ်မီးလောင် တွေ့ရှိ',
    }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('safesphere_language');
        return (saved === 'en' || saved === 'de' || saved === 'my') ? saved : 'en';
    });

    useEffect(() => {
        localStorage.setItem('safesphere_language', language);
    }, [language]);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
    };

    const t = (key: string): string => {
        return translations[language][key as keyof typeof translations['en']] || key;
    };

    const translateDescription = (desc: string): string => {
        const key = DESC_KEYS[desc];
        return key ? t(key) : desc;
    };

    const translateReportType = (type: string): string => {
        const key = REPORT_TYPE_KEYS[type?.toUpperCase()];
        return key ? t(key) : type;
    };

    const translateAlertTitle = (title: string): string => {
        const key = ALERT_TITLE_KEYS[title];
        return key ? t(key) : title;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, translateDescription, translateReportType, translateAlertTitle }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
